<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('MyUNHCR Admin'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <script>
        var themerPrimaryColor = '#DA4C4C';

        var basePath = '',
            commonPath = '../public/',


        // charts data
            charts_data = {

                // 24 hours
                graph24hours: {
                    from: 1381874400000,
                    to: 1381960800000			},

                // 7 days
                graph7days: {
                    from: 1381356000000,
                    to: 1381960800000			},

                // 14 days
                graph14days: {
                    from: 1380751200000,
                    to: 1381960800000			},

                // main dashboard graph - website traffic
                website_traffic: {
                    d1: [[1379455200000, 2173],[1379541600000, 2964],[1379628000000, 3048],[1379714400000, 2609],[1379800800000, 3731],[1379887200000, 2772],[1379973600000, 2677],[1380060000000, 2154],[1380146400000, 2749],[1380232800000, 2889],[1380319200000, 3293],[1380405600000, 3906],[1380492000000, 2573],[1380578400000, 3068],[1380664800000, 2709],[1380751200000, 3707],[1380837600000, 3018],[1380924000000, 3440],[1381010400000, 2842],[1381096800000, 2873],[1381183200000, 3623],[1381269600000, 2650],[1381356000000, 3825],[1381442400000, 2850],[1381528800000, 3707],[1381615200000, 2569],[1381701600000, 3999],[1381788000000, 3680],[1381874400000, 2852],[1381960800000, 2335]],
                    d2: [[1379455200000, 643],[1379541600000, 690],[1379628000000, 630],[1379714400000, 412],[1379800800000, 654],[1379887200000, 471],[1379973600000, 569],[1380060000000, 628],[1380146400000, 477],[1380232800000, 639],[1380319200000, 621],[1380405600000, 486],[1380492000000, 498],[1380578400000, 412],[1380664800000, 422],[1380751200000, 414],[1380837600000, 615],[1380924000000, 614],[1381010400000, 424],[1381096800000, 402],[1381183200000, 464],[1381269600000, 698],[1381356000000, 595],[1381442400000, 526],[1381528800000, 402],[1381615200000, 427],[1381701600000, 508],[1381788000000, 565],[1381874400000, 620],[1381960800000, 486]]
                }

            };


        var primaryColor = '#4a8bc2',
            dangerColor = '#b55151',
            successColor = '#609450',
            warningColor = '#ab7a4b',
            inverseColor = '#45484d';

        //Load the Visualization API and the piechart package.
        //        google.load('visualization', '1.0', {'packages':['table', 'corechart']});

        // Set a callback to run when the Google Visualization API is loaded.
        //        google.setOnLoadCallback(charts.traffic_sources_dataTables.init);

    </script>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/scripts/plugins/color/jquery-miniColors/jquery.miniColors.css')
        ->prependStylesheet($this->basePath() . '/scripts/plugins/other/google-code-prettify/prettify.css')
        ->prependStylesheet($this->basePath() . '/scripts/plugins/forms/pixelmatrix-uniform/css/uniform.default.css')
        ->prependStylesheet($this->basePath() . '/extend/bootstrap-switch/static/stylesheets/bootstrap-switch.css')
        ->prependStylesheet($this->basePath() . '/extend/bootstrap-select/bootstrap-select.css')
        ->prependStylesheet($this->basePath() . '/css/font-awesome/css/font-awesome.min.css')
        ->prependStylesheet($this->basePath() . '/css/glyphicons.css')
        ->prependStylesheet($this->basePath() .
            '/scripts/plugins/system/jquery-ui-1.9.2.custom/css/smoothness/jquery-ui-1.9.2.custom.min.css')
        ->prependStylesheet($this->basePath() . '/scripts/plugins/notifications/Gritter/css/jquery.gritter.css')
        ->prependStylesheet($this->basePath() . '/scripts/plugins/notifications/notyfy/themes/default.css')
        ->prependStylesheet($this->basePath() . '/scripts/plugins/notifications/notyfy/jquery.notyfy.css')
        ->prependStylesheet($this->basePath() . '/scripts/plugins/forms/select2/select2.css')
        ->prependStylesheet($this->basePath() . '/extend/bootstrap-wysihtml5/css/bootstrap-wysihtml5-0.0.2.css')
        ->prependStylesheet($this->basePath() . '/extend/jasny-bootstrap/css/jasny-bootstrap-responsive.min.css')
        ->prependStylesheet($this->basePath() . '/extend/jasny-bootstrap/css/jasny-bootstrap.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css'); ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/helper.js')
        ->prependFile($this->basePath() . '/js/handle.js')
        ->prependFile($this->basePath() . '/scripts/plugins/notifications/notyfy/jquery.notyfy.js')
        ->prependFile($this->basePath() . '/scripts/plugins/notifications/Gritter/js/jquery.gritter.min.js')
        ->prependFile($this->basePath() . '/scripts/plugins/other/google-code-prettify/prettify.js')
        ->prependFile($this->basePath() . '/scripts/demo/layout.js')
        ->prependFile($this->basePath() . '/extend/bootstrap-wysihtml5/js/bootstrap-wysihtml5-0.0.2.js')
        ->prependFile($this->basePath() . '/extend/bootstrap-wysihtml5/js/wysihtml5-0.3.0_rc2.min.js')
        ->prependFile($this->basePath() . '/extend/bootbox.js')
        ->prependFile($this->basePath() . '/extend/jasny-bootstrap/js/bootstrap-fileupload.js')
        ->prependFile($this->basePath() . '/extend/jasny-bootstrap/js/jasny-bootstrap.min.js')
        ->prependFile($this->basePath() . '/extend/bootstrap-hover-dropdown/twitter-bootstrap-hover-dropdown.min.js')
        ->prependFile($this->basePath() . '/extend/bootstrap-switch/static/js/bootstrap-switch.min.js')
        ->prependFile($this->basePath() . '/extend/bootstrap-select/bootstrap-select.js')
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/scripts/plugins/forms/pixelmatrix-uniform/jquery.uniform.min.js')
        ->prependFile($this->basePath() . '/scripts/plugins/other/jquery.ba-resize.js')
        ->prependFile($this->basePath() . '/scripts/demo/charts.helper.js')
        ->prependFile($this->basePath() . '/scripts/plugins/charts/flot/jquery.flot.orderBars.js')
        ->prependFile($this->basePath() . '/scripts/plugins/charts/flot/jquery.flot.resize.js')
        ->prependFile($this->basePath() . '/scripts/plugins/charts/flot/jquery.flot.selection.js')
        ->prependFile($this->basePath() . '/scripts/plugins/charts/flot/jquery.flot.tooltip.js')
        ->prependFile($this->basePath() . '/scripts/plugins/charts/flot/jquery.flot.pie.js')
        ->prependFile($this->basePath() . '/scripts/plugins/charts/flot/jquery.flot.js')
        ->prependFile($this->basePath() . '/scripts/plugins/charts/sparkline/jquery.sparkline.js')
//        ->prependFile($this->basePath() . '/scripts/demo/themer.js')
        ->prependFile($this->basePath() . '/scripts/plugins/system/jquery.cookie.js')
        //->prependFile($this->basePath() . '/scripts/demo/twitter.js')
        ->prependFile($this->basePath() . '/scripts/plugins/other/holder/holder.js')
        ->prependFile($this->basePath() . '/scripts/demo/common.js')
        ->prependFile($this->basePath() . '/scripts/plugins/other/jquery-slimScroll/jquery.slimscroll.min.js')
        ->prependFile($this->basePath() . '/scripts/plugins/forms/select2/select2.js')
        ->prependFile($this->basePath() . '/scripts/plugins/color/jquery-miniColors/jquery.miniColors.js')
        ->prependFile($this->basePath() . '/scripts/plugins/system/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js')
        ->prependFile($this->basePath() . '/scripts/plugins/system/jquery-ui-1.9.2.custom/js/jquery-ui-1.9.2.custom.min.js')
        ->prependFile($this->basePath() . '/scripts/plugins/system/less-1.3.3.min.js')
        ->prependFile($this->basePath() . '/scripts/plugins/system/modernizr.custom.76094.js')
        ->prependFile($this->basePath() . '/scripts/plugins/system/jquery-1.8.2.min.js'); ?>
</head>
<body>

<!-- Start Content -->
<div class="first-container container fluid login">

    <?php echo $this->partial('partial/topNavigation.phtml'); ?>

    <div id="wrapper">

        <div id="menu" class="hidden-sm hidden-print">
            <div id="menuInner">
                <!-- Scrollable menu wrapper with Maximum height -->
                <div class="slim-scroll" data-scroll-height="420px">

                    <div id="search">
                        <input type="text" placeholder="Quick search ..." />
                        <button class="glyphicons search"></button>
                    </div>

                    <?php echo $this->navigation('navigation')->menu()->setPartial('partial/mainNavigation.phtml'); ?>

                </div>
            </div>
        </div>

        <div id="content" style="min-height: 600px">
            <?php if ($this->flashMessenger()->hasMessages()) { ?>
                <div class="alert alert-danger">

                    <?php
                    $messages = $this->flashMessenger()->getMessages();
                    foreach($messages as $message) {
                        echo $this->translate($message);
                    } ?>
                </div>
            <?php } ?>

            <!-- Echo Content -->
            <?php echo $this->content; ?>

        </div>

    </div>

</div>

<!--<div id="themer" class="collapse">-->
<!--    <div class="wrapper">-->
<!--        <span class="close2">&times; close</span>-->
<!--        <h4>--><?php //echo $this->translate('Themer'); ?><!-- <span>--><?php //echo $this->translate('color options'); ?><!--</span></h4>-->
<!--        <ul>-->
<!--            <li>--><?php //echo $this->translate('Theme'); ?><!--: <select id="themer-theme" class="pull-right"></select>-->
<!--                <div class="clearfix"></div></li>-->
<!--            <li>--><?php //echo $this->translate('Primary Color'); ?><!--: <input type="text" data-type="minicolors"-->
<!--                data-default="#ffffff" data-slider="hue" data-textfield="false" data-position="left"-->
<!--                id="themer-primary-cp" /><div class="clearfix"></div></li>-->
<!--            <li>-->
<!--                <span class="link" id="themer-custom-reset">--><?php //echo $this->translate('reset theme'); ?><!--</span>-->
<!--                <span class="pull-right"><label>--><?php //echo $this->translate('advanced'); ?>
<!--                        <input type="checkbox" value="1" id="themer-advanced-toggle" /></label></span>-->
<!--            </li>-->
<!--        </ul>-->
<!--        <div id="themer-getcode" class="hide">-->
<!--            <hr class="separator" />-->
<!--            <button class="btn btn-primary btn-small pull-right btn-icon glyphicons download"-->
<!--                    id="themer-getcode-less"><i></i>--><?php //echo $this->translate('Get LESS'); ?><!--</button>-->
<!--            <button class="btn btn-inverse btn-small pull-right btn-icon glyphicons download"-->
<!--                    id="themer-getcode-css"><i></i>--><?php //echo $this->translate('Get CSS'); ?><!--</button>-->
<!--            <div class="clearfix"></div>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->

<div class="modal fade" id="activateCountryModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title"><?php echo $this->translate('Set active country'); ?></h4>
            </div>
            <div class="modal-body">
                <select id="activateCountrySelect" style="width:100%"></select>
            </div>
            <div class="modal-footer">
                <a type="button" class="btn btn-primary" data-activateCountrySubmit
                   data-href="<?php echo $this->url('countrySelection'); ?>">Set country</a>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<div class="separator bottom"></div>

<script>
    Holder.add_theme("dark", {background:"#000", foreground:"#aaa", size:9})
</script>
</body>
</html>
