<div class='feedback -positive gapSmall'>
    <i class='feedback_icon icon'></i>

    <h1 class='feedback_title'><?php echo $this->translate('Your report has been sent!'); ?></h1>

    <div class='feedback_description preformat'>
        <p>Some useful information here lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt rem
            asperiores at quisquam officiis praesentium!</p>
    </div>
</div>
<a href='/menu-page.html' class='button -fullWidth' ajaxNav tabindex='0'><?php echo $this->translate('Back to
Homepage'); ?></a>
