<div class='form_item <?php if (isset($form->getMessages()['anonymous'])) echo '-error'; ?>'>
    <label class='form_label' for=''><?php echo $this->translate('Is this report Anonymous ?'); ?></label>

    <div class='grid -collapse -clean'>
        <div class='grid_column -small6 form_subitem'>
            <div class='bigRadio'>
                <input class='bigRadio_input' type='radio' name='anonymous' value='1' id='anonymous-yes'
                    <?php if ($form->get('anonymous')->getValue() === '1') echo 'checked'; ?>
                    >
                <label class='bigRadio_label' for='anonymous-yes'><?php echo $this->translate('Yes'); ?></label>
            </div>
        </div>
        <div class='grid_column -small6 form_subitem'>
            <div class='bigRadio'>
                <input class='bigRadio_input' type='radio' name='anonymous' value='0' id='anonymous-no'
                    <?php if ($form->get('anonymous')->getValue() === '0') echo 'checked'; ?>
                    >
                <label class='bigRadio_label' for='anonymous-no'><?php echo $this->translate('No'); ?></label>
            </div>
        </div>
    </div>

    <?php if (isset($form->getMessages()['anonymous'])) { ?>
        <div class="form_error"><?php echo reset($form->getMessages()['anonymous']); ?></div>
    <?php } ?>

</div>



<input id="fileupload" type="file" name="files[]" data-url="<?php echo $this->url('uploadFile'); ?>" multiple fileUpload>



<div class='form_item <?php if (isset($form->getMessages()['category'])) echo '-error'; ?>'>
    <label class='form_label'
           for='incidentCategory'><?php echo $this->translate('Category of the Incident:'); ?></label>

    <div class='form_field customSelect'>
        <?php echo $this->formRow($form->get('category')); ?>
        <a unselectable='on'
           class='customSelect_overlay'>
            <?php
            if ($form->get('category')->getValue()) {
                $displayValue = $form->get('category')->getValueOptions()[$form->get('category')->getValue()];
            } else {
                $displayValue = array_values($form->get('category')->getValueOptions())[0];
            }
            ?>
            <?php echo $this->translate($displayValue); ?>
        </a>
    </div>
</div>

<div class='form_item <?php if (isset($form->getMessages()['type'])) echo '-error'; ?>'>
    <label class='form_label'
           for='protectionType'><?php echo $this->translate('Which type of protection incident?'); ?></label>

    <div class='form_field customSelect'>
        <?php echo $this->formRow($form->get('type')); ?>
        <a unselectable='on' class='customSelect_overlay'>
            <?php
            if ($form->get('type')->getValue()) {
                $displayValue = $form->get('type')->getValueOptions()[$form->get('type')->getValue()];
            } else {
                $displayValue = array_values($form->get('type')->getValueOptions())[0];
            }
            ?>
            <?php echo $this->translate($displayValue); ?>
        </a>
    </div>
</div>

<div class='grid -compact -reverse'>
    <div class='grid_column -small7'>
        <?php echo $this->formRow($form->get('submit')); ?>
    </div>
    <div class='grid_column -small5'>
        <a class='button -fullWidth' href='/menu-page.html' ajaxNav tabindex='0'><?php echo $this->translate('Cancel');
            ?></a>
    </div>
</div>
