<div class='form_item <?php if (isset($form->getMessages()['description'])) echo '-error'; ?>'>
    <label class='form_label'
           for='feedbackMessage'><?php echo $this->translate('Please describe the incident:'); ?></label>

    <div class='form_field'>
        <?php echo $this->formRow($form->get('description')); ?>
    </div>
</div>

<div class='grid -compact -reverse'>
    <div class='grid_column -small7'>
        <?php echo $this->formRow($form->get('submit')); ?>
    </div>
    <div class='grid_column -small5'>
        <a class='button -fullWidth' href='<?php echo $this->url('reportAnIncident', array(),
            array('query' => array('step' => $step - 1))); ?>' ajaxNav tabindex='0'><?php echo $this->translate('Back'); ?></a>
    </div>
</div>
