<h2 class='form_legend'><?php echo $this->translate('Where did this happen?'); ?></h2>

<div class='form_item'>
    <label class='form_label' for='report_country'><?php echo $this->translate('Country'); ?></label>

    <div class='form_field customSelect'>
        <?php echo $this->formRow($form->get('country')); ?>
        <a unselectable='on' class='customSelect_overlay'>
            <?php
            if ($form->get('country')->getValue()) {
                $displayValue = $form->get('country')->getValueOptions()[$form->get('country')->getValue()];
            } else {
                $displayValue = array_values($form->get('country')->getValueOptions())[0];
            }
            ?>
            <?php echo $this->translate($displayValue); ?>
        </a>
    </div>
</div>

<div class='form_item'>
    <label class='form_label' for='report_location'><?php echo $this->translate('Location'); ?></label>

    <div class='form_field'>
        <?php echo $this->formRow($form->get('address')); ?>
    </div>
</div>

<div class='grid -compact -reverse'>
    <div class='grid_column -small7'>
        <?php echo $this->formRow($form->get('submit')); ?>
    </div>
    <div class='grid_column -small5'>
        <a class='button -fullWidth' href='<?php echo $this->url('reportAnIncident', array(),
            array('query' => array('step' => $step - 2))); ?>' ajaxNav tabindex='0'><?php echo $this->translate('Back'); ?></a>
    </div>
</div>
