<div class='form_item fileUpload'>
    <label class='form_label fileUpload_label' for='feedbackMessage'>
        <?php echo $this->translate('Would you like to take/upload a picture of the incident? (optional)'); ?>
        <?php echo $this->formRow($form->get('image')); ?>
    </label>
</div>

<div class='form_item fileUpload'>
    <label class='form_label fileUpload_label' for='feedbackMessage'>
        <?php echo $this->translate('Would you like to record your testimony of the incident? (optional)'); ?>
        <?php echo $this->formRow($form->get('audio')); ?>
    </label>
</div>

<div class='grid -compact -reverse'>
    <div class='grid_column -small7'>
        <?php $form->get('submit')->setAttribute('value', 'Report'); ?>
        <?php echo $this->formRow($form->get('submit')); ?>
    </div>
    <div class='grid_column -small5'>
        <a class='button -fullWidth' href='<?php echo $this->url('reportAnIncident', array(),
            array('query' => array('step' => $step - 2))); ?>' ajaxNav tabindex='0'><?php echo $this->translate('Back'); ?></a>
    </div>
</div>
