<?php $form = $this->form; ?>
<?php $form->setAttribute('class', 'form-horizontal margin-none'); ?>
<?php $form->setAttribute('action', $this->url('survey/add'))->prepare(); ?>

<div class="separator bottom"></div>
<h3 class="glyphicons keynote"><?php echo $this->translate('Add ODK survey'); ?></h3>
<div class="innerLR">

    <?php echo $this->form()->openTag($form); ?>

    <div class="widget-body col-md-12">
        <div class="tab-content">
            <div class="row">

                <label><?php echo $this->translate('ODK survey file'); ?></label>
                <?php echo $this->formRow($form->get('file')); ?>
                <div class="separator bottom"></div>

            </div>

            <div class="separator"></div>
            <div class="form-group" style="padding-right: 15px;">
                <button type="submit" class="btn btn-icon btn-primary glyphicons circle_ok pull-right"><i></i>
                    <?php echo $this->translate('Upload file'); ?></button>
            </div>
        </div>
    </div>

    <?php echo $this->form()->closeTag($form); ?>

</div>
