<div class="separator bottom"></div>
    <div class="heading-buttons">
        <h3 class="glyphicons notes_2"><?php echo $this->translate('Surveys'); ?></h3>
        <div class="buttons pull-right">
            <a class="btn btn-primary btn-icon glyphicons circle_plus" href="<?php echo $this->url('survey/add');?>">
                <?php echo $this->translate('Add ODK survey'); ?></a>
        </div>
        <div class="clearfix" style="clear: both;"></div>
    </div>
<div class="separator bottom"></div>

<div class="innerLR">

    <div class="widget widget-4">
        <div class="widget-head">
            <h4 class="heading"><?php echo $this->translate('Surveys'); ?></h4>
        </div>
        <div class="widget-body">
            <?php if (count($this->data) > 0) { ?>
                <table class="dynamicTable table table-striped table-bordered table-primary table-condensed colVis">
                    <thead>
                        <tr>
                            <th><?php echo $this->translate('Name'); ?></th>
                            <th><?php echo $this->translate('Active'); ?></th>
                            <th><?php echo $this->translate('Action'); ?></th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach($this->data as $data) { ?>
                        <tr data-row="row_<?php echo $data->getId(); ?>">
                            <td><?php echo $data->getName(); ?></td>
                            <td><?php echo $data->getActive() == 1 ? '<input type="checkbox" data-activeCheck data-href="'
                                    . $this->url('survey/manageActiveStatus', array('id' => $data->getId())) . '" checked>'
                                    : '<input type="checkbox" data-activeCheck data-href="'
                                    . $this->url('survey/manageActiveStatus', array('id' => $data->getId())) . '">'; ?></td>
                            <td>
                                <a class="btn-action glyphicons remove_2 btn-danger" href="#" data-delete
                                   data-href="<?php echo $this->url('survey/delete', array('id' => $data->getId())); ?>"></a>
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
            <?php } else { ?>
                <div class="widget-body center">
                    <span class="gritter-add-regular btn btn-inverse btn-block">
                        <?php echo $this->translate('No surveys found. Please upload new one.'); ?>
                    </span>
                </div>
            <?php } ?>
        </div>
    </div>

    <div class="separator bottom"></div>

    <h3 class="glyphicons notes"><?php echo $this->translate('Added surveys'); ?></h3>
    <?php if (count($this->surveys) > 0) { ?>
        <?php foreach ($this->surveys as $surveyId => $surveyFile) { ?>
            <a href="<?php  echo $this->url('survey/downloadSurvey', array('id' => $surveyId)); ?>">
                <div class="col-md-3 widget-stats">
                    <span class="txt"><strong><?php echo $surveyFile; ?></strong>
                        <?php echo $this->translate('Filename') . ': ' . $surveyFile; ?>
                    </span>
                </div>
            </a>
        <?php } ?>
    <?php } else { ?>
        <div class="widget-body center">
            <span class="gritter-add-regular btn btn-inverse btn-block">
                <?php echo $this->translate('No surveys found. Please upload new one.'); ?></span>
        </div>
    <?php } ?>

</div>

<div class="clearfix" style="clear: both;"></div>

<?php
echo $this->paginationControl(
    $this->data,
    'sliding',
    array('partial/paginator.phtml', 'Administration'),
    array('route  ' => 'survey', 'routeParams' => array())
);
?>
