<?php $form = $this->form; ?>
<?php $form->setAttribute('class', 'form-horizontal margin-none'); ?>
<?php $form->setAttribute('action', $this->url('survey'))->prepare(); ?>
<?php $form->prepare(); ?>

<div class="separator bottom"></div>
<h3 class="glyphicons notes_2"><?php echo $this->translate('Surveys'); ?></h3>
<div class="innerLR">

    <?php echo $this->form()->openTag($form); ?>

    <div class="widget-body col-md-12">
        <div class="tab-content">
            <div class="row">

                <label><?php echo $this->translate('ODK survey file'); ?></label>
                <?php echo $this->formRow($form->get('file')); ?>
                <div class="separator bottom"></div>

            </div>

            <div class="separator"></div>
            <div class="form-group" style="padding-right: 15px;">
                <button type="submit" class="btn btn-icon btn-primary glyphicons circle_ok pull-right"><i></i>
                    <?php echo $this->translate('Upload file'); ?></button>
            </div>
        </div>
    </div>

    <?php echo $this->form()->closeTag($form); ?>

    <div class="separator bottom"></div>
    <h3 class="glyphicons notes"><?php echo $this->translate('Added surveys'); ?></h3>
    <?php if (count($this->surveys) > 0) { ?>
        <?php foreach ($this->surveys as $surveyId => $surveyFile) { ?>
            <a href="<?php  echo $this->url('translation/downloadTranslation', array('id' => $surveyId)); ?>">
                <div class="col-md-3 widget-stats">
                    <span class="txt"><strong><?php echo $surveyFile; ?></strong>
                        <?php echo $this->translate('Filename') . ': ' . $surveyFile; ?>
                    </span>
                </div>
            </a>
        <?php } ?>
    <?php } else { ?>
        <div class="widget-body center">
            <span class="gritter-add-regular btn btn-inverse btn-block">
                <?php echo $this->translate('No surveys found. Please upload new one.'); ?></span>
        </div>
    <?php } ?>

</div>
