
<?php $form = $this->form; ?>
<?php $form->setAttribute('class', 'form-horizontal margin-none'); ?>
<?php $form->setAttribute('action', $this->url('account/add'))->prepare(); ?>
<?php $form->prepare(); ?>

<div class="separator bottom"></div>
<h3 class="glyphicons user"><?php echo $this->translate('Add user'); ?></h3>
<div class="innerLR">

    <?php echo $this->form()->openTag($form); ?>

        <div class="widget-body col-md-12">
            <div class="tab-content">
                <!-- Row -->
                <div class="row">
                    <!-- Column -->
                    <div class="col-md-6">

                        <label><?php echo $this->translate('Email'); ?></label>
                        <?php echo $this->formRow($form->get('email')); ?>
                        <div class="separator bottom"></div>

                        <label><?php echo $this->translate('Type'); ?></label>
                        <?php echo $this->formRow($form->get('type')); ?>
                        <div class="separator bottom"></div>

                    </div>
                    <div class="col-md-6">

                        <label><?php echo $this->translate('Password'); ?></label>
                        <?php echo $this->formRow($form->get('password')); ?>
                        <div class="separator bottom"></div>

                        <label><?php echo $this->translate('Confirm Password'); ?></label>
                        <?php echo $this->formRow($form->get('confirmPassword')); ?>
                        <div class="separator bottom"></div>

                    </div>
                </div>

                <div class="separator"></div>
                <div class="form-group" style="padding-right: 15px;">
                    <button type="submit" class="btn btn-icon btn-primary glyphicons circle_ok pull-right"><i></i>
                        <?php echo $this->translate('Add user'); ?></button>
                </div>
            </div>
        </div>

    <?php echo $this->form()->closeTag($form); ?>

</div>
