
<div class="separator bottom"></div>
    <div class="heading-buttons">
        <h3 class="glyphicons table"><?php echo $this->translate('Accounts'); ?></h3>

        <div class="buttons pull-right">
            <a class="btn btn-primary btn-icon glyphicons user_add" href="<?php echo $this->url('account/add');?>">
                <?php echo $this->translate('Add new user'); ?></a>
        </div>
        <div class="clearfix" style="clear: both;"></div>
    </div>
<div class="separator bottom"></div>

<div class="innerLR">
    <div class="widget widget-4">
        <div class="widget-head">
            <h4 class="heading"><?php echo $this->translate('User Accounts'); ?></h4>
        </div>
        <div class="widget-body">
            <table class="dynamicTable table table-striped table-bordered table-primary table-condensed colVis">
                <thead>
                    <tr>
                        <th><?php echo $this->translate('#'); ?></th>
                        <th><?php echo $this->translate('Email'); ?></th>
                        <th><?php echo $this->translate('Type'); ?></th>
                        <th><?php echo $this->translate('Action'); ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->data as $data) { ?>
                        <tr data-row="row_<?php echo $data->getId(); ?>">
                            <td><?php echo $data->getId(); ?></td>
                            <td><?php echo $data->getEmail(); ?></td>
                            <td><?php echo ucfirst($data->getType()); ?></td>
                            <td>
                                <a class="btn-action glyphicons pencil btn-success"
                                   href="<?php echo $this->url('account/edit', array('id' => $data->getId())); ?>"></a>
                                <a class="btn-action glyphicons remove_2 btn-danger" href="#" data-delete="true"
                                   data-href="<?php echo $this->url('account/delete', array('id' => $data->getId())); ?>"></a>
                            </td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?php
echo $this->paginationControl(
    $this->data,
    'sliding',
    array('partial/paginator.phtml', 'Administration'),
    array('route  ' => 'account', 'routeParams' => array())
);
?>


<script>

    $('[data-delete="true"]').on('click', function(e){

        e.preventDefault();
        if (confirm('You will remove selected user account, do you want to continue?')) {
            $.ajax({
                type: 'POST',
                url: $(this).data('href'),
                success: function(response){
                   $('[data-row="row_' + response.userId + '"]').fadeOut(500);
                },
                error: function() {
                    console.log('Error on account delete');
                }
            });

        }
    });
</script>
