
  <?php
  // add new task form
  $form = $this->form;

  $form->setAttribute('action', $this->url('security/users',
      array(
          'action'     => 'profile',
          'id'     => $this->id,
      )
  ))->prepare();

  echo $this->form()->openTag($form);

  echo $this->formRow($form->get('id'));
  echo $this->formRow($form->get('email')->setAttributes(array('readonly' => 'readonly', 'autocomplete' => 'off')));
  echo $this->formRow($form->get('oldPassword')->setAttribute('autocomplete', 'off'));
  echo $this->formRow($form->get('password'));
  echo $this->formRow($form->get('confirmPassword'));
  echo $this->formRow($form->get('admin')->setAttribute('onclick', 'return false'));
  echo $this->formRow($form->get('firstName'));
  echo $this->formRow($form->get('lastName'));
  echo $this->formRow($form->get('favouriteTaskType'));
  echo $this->formRow($form->get('submit'));

  echo $this->form()->closeTag($form);

  ?>
