<div class="separator bottom"></div>

<div class="heading-buttons">
    <h3 class="glyphicons notes"> <?php echo $this->translate('Complaint preview'); ?></h3>

    <div class="clearfix" style="clear: both;"></div>
</div>

<div class="separator bottom"></div>

<div class="innerLR" data-checkActiveCountry>
    <div class="widget widget-4">

        <div class="clearfix" style="clear: both;"></div>

        <div class="well">
            <table class="table table-invoice">
                <tbody>
                <tr>
                    <td style="width: 50%;">
                        <p class="lead"><?php echo $this->complaint->getContent(); ?></p>
                    </td>
                    <td class="right">
                        <h4 class="lead"><?php echo $this->translate('Date'); ?></h4>
                        <h4><?php echo date_format($this->complaint->getDate(), 'd.m.Y H:i:s'); ?></h4>

                        <h4 class="lead"><?php echo $this->translate('Country'); ?></h4>
                        <h4><?php echo $this->complaint->getCountry()->getName(); ?></h4>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
