
<?php $form = $this->form; ?>
<?php $form->setAttribute('class', 'form-horizontal margin-none'); ?>
<?php $form->setAttribute('action', $this->url('service/editPartner', array('id' => $this->servicePartnerId)))->prepare(); ?>

<div class="separator bottom"></div>
<h3 class="glyphicons keynote"><?php echo $this->translate('Edit Service Partner'); ?></h3>
<div class="innerLR" data-checkActiveCountry>

    <?php echo $this->form()->openTag($form); ?>

    <div class="widget-body col-md-12">
        <div class="tab-content">
            <!-- Row -->
            <div class="row">
                <!-- Column -->
                <div class="col-md-6">

                    <label><?php echo $this->translate('Partner Name'); ?></label>
                    <?php echo $this->formRow($form->get('partnerName')); ?>
                    <div class="separator bottom"></div>

                    <label><?php echo $this->translate('Partner Acronym'); ?></label>
                    <?php echo $this->formRow($form->get('partnerAcronym')); ?>
                    <div class="separator bottom"></div>

                </div>
                <div class="col-md-6">

                    <label><?php echo $this->translate('Partner Url'); ?></label>
                    <?php echo $this->formRow($form->get('partnerUrl')); ?>
                    <div class="separator bottom"></div>

                    <label><?php echo $this->translate('Description'); ?></label>
                    <?php echo $this->formRow($form->get('description')); ?>
                    <div class="separator bottom"></div>

                </div>
            </div>

            <div class="separator"></div>
            <div class="form-group" style="padding-right: 15px;">
                <button type="submit" class="btn btn-icon btn-primary glyphicons circle_ok pull-right"><i></i>
                    <?php echo $this->translate('Save changes'); ?></button>
            </div>
        </div>
    </div>

    <?php echo $this->form()->closeTag($form); ?>

</div>
