
<?php $form = $this->form; ?>
<?php $form->setAttribute('class', 'form-horizontal margin-none'); ?>
<?php $form->setAttribute('action', $this->url('service/editActivity', array('id' => $this->activityId)))->prepare(); ?>

<div class="separator bottom"></div>
<h3 class="glyphicons keynote"><?php echo $this->translate('Edit Service Activity'); ?></h3>
<div class="innerLR" data-checkActiveCountry>

    <?php echo $this->form()->openTag($form); ?>

        <div class="widget-body col-md-12">
            <div class="tab-content">
                <!-- Row -->
                <div class="row">
                    <!-- Column -->
                    <div class="col-md-12">

                        <label><?php echo $this->translate('Activity Name'); ?></label>
                        <?php echo $this->formRow($form->get('activityName')); ?>
                        <div class="separator bottom"></div>

                        <label><?php echo $this->translate('Activity Category'); ?></label>
                        <?php echo $this->formRow($form->get('activityCategory')); ?>
                        <div class="separator bottom"></div>

                        <label><?php echo $this->translate('Activity Start'); ?></label>
                        <?php echo $this->formRow($form->get('activityStart')); ?>
                        <div class="separator bottom"></div>

                        <label><?php echo $this->translate('Activity End'); ?></label>
                        <?php echo $this->formRow($form->get('activityEnd')); ?>
                        <div class="separator bottom"></div>

                    </div>
                </div>

                <div class="separator"></div>
                <div class="form-group" style="padding-right: 15px;">
                    <button type="submit" class="btn btn-icon btn-primary glyphicons circle_ok pull-right"><i></i>
                        <?php echo $this->translate('Save changes'); ?></button>
                </div>
            </div>
        </div>

    <?php echo $this->form()->closeTag($form); ?>

</div>
