
<?php $form = $this->form; ?>
<?php $form->setAttribute('class', 'form-horizontal margin-none'); ?>
<?php $form->setAttribute('action', $this->url('service/editService', array('id' => $this->serviceId)))->prepare(); ?>

<div class="separator bottom"></div>
<h3 class="glyphicons circle_info"><?php echo $this->translate('Edit Service'); ?></h3>
<div class="innerLR" data-checkActiveCountry>

    <?php echo $this->form()->openTag($form); ?>

    <div class="widget-body col-md-12">
        <div class="tab-content">
            <!-- Row -->
            <div class="row">
                <div class="col-md-6">

                    <label><?php echo $this->translate('Service name'); ?></label>
                    <?php echo $this->formRow($form->get('serviceName')); ?>
                    <div class="separator bottom"></div>

                    <label><?php echo $this->translate('Service acronym'); ?></label>
                    <?php echo $this->formRow($form->get('serviceAcronym')); ?>
                    <div class="separator bottom"></div>

                    <label><?php echo $this->translate('Description'); ?></label>
                    <?php echo $this->formRow($form->get('description')); ?>
                    <div class="separator bottom"></div>

                    <label><?php echo $this->translate('Service URL'); ?></label>
                    <?php echo $this->formRow($form->get('serviceUrl')); ?>
                    <div class="separator bottom"></div>

                </div>
                <div class="col-md-6">

                    <label><?php echo $this->translate('Latitude'); ?></label>
                    <?php echo $this->formRow($form->get('latitude')); ?>
                    <div class="separator bottom"></div>

                    <label><?php echo $this->translate('Longitude'); ?></label>
                    <?php echo $this->formRow($form->get('longitude')); ?>
                    <div class="separator bottom"></div>

                    <label><?php echo $this->translate('Service Organization'); ?></label>
                    <?php echo $this->formRow($form->get('organization')); ?>
                    <div class="separator bottom"></div>

                    <label><?php echo $this->translate('Service Sector'); ?></label>
                    <?php echo $this->formRow($form->get('sector')); ?>
                    <div class="separator bottom"></div>

                    <label><?php echo $this->translate('Service Activity'); ?></label>
                    <?php echo $this->formRow($form->get('activity')); ?>
                    <div class="separator bottom"></div>

                </div>
            </div>

            <div class="separator"></div>
            <div class="form-group" style="padding-right: 15px;">
                <button type="submit" class="btn btn-icon btn-primary glyphicons circle_ok pull-right"><i></i>
                    <?php echo $this->translate('Save changes'); ?></button>
            </div>
        </div>
    </div>

    <?php echo $this->form()->closeTag($form); ?>

</div>
