<?php $form = $this->form; ?>
<?php $form->setAttribute('class', 'form-horizontal margin-none'); ?>
<?php $form->setAttribute('action', $this->url('translation'))->prepare(); ?>
<?php $form->prepare(); ?>

<div class="separator bottom"></div>
<h3 class="glyphicons translate"><?php echo $this->translate('Translations'); ?></h3>
<div class="innerLR" style="min-height: 500px">

    <?php echo $this->form()->openTag($form); ?>

    <div class="widget-body col-md-12">
        <div class="tab-content">
            <div class="row">
                <label><?php echo $this->translate('Translation file'); ?></label>
                <?php echo $this->formRow($form->get('translation-file')); ?>
                <div class="separator bottom"></div>

                <label><?php echo $this->translate('Translation locale'); ?></label>
                <?php echo $this->formRow($form->get('locale')); ?>
                <div class="separator bottom"></div>
            </div>

            <div class="separator"></div>
            <div class="form-group" style="padding-right: 15px;">
                <button type="submit" class="btn btn-icon btn-primary glyphicons circle_ok pull-right"><i></i>
                    <?php echo $this->translate('Upload file'); ?></button>
            </div>
        </div>
    </div>

    <?php echo $this->form()->closeTag($form); ?>

    <div class="separator bottom"></div>
    <h3 class="glyphicons notes"><?php echo $this->translate('Added translations'); ?></h3>
    <div class="row">
        <?php foreach ($this->translations as $translation => $translationFile) { ?>
            <div class="col-md-2 widget-stats">
                <span class="txt"><strong><?php echo $translation; ?></strong>
                    <?php echo $this->translate('Filename') . ': ' . $translationFile; ?>
                </span>
            </div>
        <?php } ?>
    </div>

</div>
