<?php $form = $this->form; ?>
<?php $form->setAttribute('class', 'form-horizontal margin-none'); ?>
<?php $form->setAttribute('action', $this->url('translation'))->prepare(); ?>
<?php $form->prepare(); ?>

<div class="separator bottom"></div>
<h3 class="glyphicons translate"><?php echo $this->translate('Translations'); ?></h3>
<div class="innerLR" style="min-height: 500px">

    <?php echo $this->form()->openTag($form); ?>

    <div class="widget-body col-md-12">
        <div class="tab-content">
            <div class="row">
                    <label><?php echo $this->translate('Translation file'); ?></label>
                    <?php echo $this->formRow($form->get('translation-file')); ?>
                    <?php echo $this->formElementErrors($form->get('translation-file')); ?>
                    <div class="separator bottom"></div>
            </div>

            <div class="separator"></div>
            <div class="form-group" style="padding-right: 15px;">
                <button type="submit" class="btn btn-icon btn-primary glyphicons circle_ok pull-right"><i></i>
                    <?php echo $this->translate('Save changes'); ?></button>
            </div>
        </div>
    </div>

    <?php echo $this->form()->closeTag($form); ?>

</div>
