<div class="separator bottom"></div>
    <div class="heading-buttons">
        <h3 class="glyphicons translate"><?php echo $this->translate('Translations'); ?></h3>
        <div class="buttons pull-right">
            <a class="btn btn-primary btn-icon glyphicons circle_plus" href="<?php echo $this->url('translation/add');?>">
                <?php echo $this->translate('Add translation'); ?></a>
        </div>
        <div class="clearfix" style="clear: both;"></div>
    </div>
<div class="separator bottom"></div>

<div class="innerLR" data-checkActiveCountry>

    <?php if (count($this->translations) > 0) { ?>
        <?php foreach ($this->translations as $translationId => $translationFile) { ?>
            <a href="<?php  echo $this->url('translation/downloadTranslation', array('id' => $translationId)); ?>">
                <div class="col-md-2 widget-stats">
                    <span class="txt"><strong><?php echo substr($translationFile, 0, 5); ?></strong>
                        <?php echo $this->translate('Filename') . ': ' . $translationFile; ?>
                    </span>
                </div>
            </a>
        <?php } ?>
    <?php } else { ?>
        <div class="widget-body center">
            <span class="gritter-add-regular btn btn-inverse btn-block">
                <?php echo $this->translate('Translations not found. Please upload new one.'); ?></span>
        </div>
    <?php } ?>

</div>
