
<?php $form = $this->form; ?>
<?php $form->setAttribute('class', 'form-horizontal margin-none'); ?>
<?php $form->setAttribute('action', $this->url('news/edit', array('id' => $this->newsId)))->prepare(); ?>
<?php $form->prepare(); ?>

<div class="separator bottom"></div>
<h3 class="glyphicons user"><?php echo $this->translate('Edit news'); ?></h3>
<div class="innerLR">

    <?php echo $this->form()->openTag($form); ?>

    <div class="widget-body col-md-12">
        <div class="tab-content">
            <!-- Row -->
            <div class="row">
                <!-- Column -->
                <div class="col-md-6">

                    <label><?php echo $this->translate('Title'); ?></label>
                    <?php echo $this->formRow($form->get('title')); ?>
                    <div class="separator bottom"></div>

                    <label><?php echo $this->translate('Content'); ?></label>
                    <?php echo $this->formRow($form->get('content')); ?>
                    <div class="separator bottom"></div>

                </div>
                <div class="col-md-6">

                    <label><?php echo $this->translate('Country'); ?></label>
                    <?php echo $this->formRow($form->get('country')); ?>
                    <div class="separator bottom"></div>

                </div>
            </div>

            <div class="separator"></div>
            <div class="form-group" style="padding-right: 15px;">
                <button type="submit" class="btn btn-icon btn-primary glyphicons circle_ok pull-right"><i></i>
                    <?php echo $this->translate('Save changes'); ?></button>
            </div>
        </div>
    </div>

    <?php echo $this->form()->closeTag($form); ?>

</div>
