
<div class="separator bottom"></div>
    <div class="heading-buttons">
        <h3 class="glyphicons keynote"><?php echo $this->translate('News'); ?></h3>

        <div class="buttons pull-right">
            <a class="btn btn-primary btn-icon glyphicons circle_plus" href="<?php echo $this->url('news/add');?>">
                <?php echo $this->translate('Add news'); ?></a>
        </div>
        <div class="clearfix" style="clear: both;"></div>
    </div>
<div class="separator bottom"></div>

<div class="innerLR" data-checkActiveCountry>
    <div class="widget widget-4">
        <div class="widget-head">
            <h4 class="heading"><?php echo $this->translate('News'); ?></h4>
        </div>
        <div class="widget-body">
            <?php if (count($this->data) > 0) { ?>
                <table class="dynamicTable table table-striped table-bordered table-primary table-condensed colVis">
                    <tbody>
                    <?php foreach($this->data as $data) { ?>
                        <tr data-row="row_<?php echo $data->getId(); ?>">
                            <td><?php echo $data->getTitle(); ?></td>
                            <td><?php echo $this->limitEcho($data->getContent()); ?></td>
                            <td><?php echo date_format($data->getDate(), 'd.m.Y'); ?></td>
                            <td>
                                <a class="btn-action glyphicons pencil btn-success"
                                   href="<?php echo $this->url('news/edit', array('id' => $data->getId())); ?>"></a>
                                <a class="btn-action glyphicons remove_2 btn-danger" href="#" data-delete
                                   data-href="<?php echo $this->url('news/delete', array('id' => $data->getId())); ?>"></a>
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
            <?php } else { ?>
                <div class="widget-body center">
                    <span class="gritter-add-regular btn btn-inverse btn-block">
                        <?php echo $this->translate('No news found. Please upload new one.'); ?>
                    </span>
                </div>
            <?php } ?>
        </div>
    </div>
</div>

<?php
echo $this->paginationControl(
    $this->data,
    'sliding',
    array('partial/paginator.phtml', 'Administration'),
    array('route  ' => 'news', 'routeParams' => array())
);
?>
