
<?php $form = $this->form; ?>
<?php $form->setAttribute('class', 'form-horizontal margin-none'); ?>
<?php $form->setAttribute('action', $this->url('settings/editActiveCountry', array('id' => $this->countryId)))->prepare(); ?>

<div class="separator bottom"></div>
<h3 class="glyphicons user"><?php echo $this->translate('Edit country languages'); ?></h3>
<div class="innerLR">

    <?php echo $this->form()->openTag($form); ?>

    <div class="widget-body col-md-12">
        <div class="tab-content">
            <!-- Row -->
            <div class="row">
                <!-- Column -->
                <div class="col-md-12">

                    <label><?php echo $this->translate('Language'); ?></label>
                    <?php echo $this->formRow($form->get('language')); ?>
                    <div class="separator bottom"></div>

                </div>
            </div>

            <div class="separator"></div>
            <div class="form-group" style="padding-right: 15px;">
                <button type="submit" class="btn btn-icon btn-primary glyphicons circle_ok pull-right"><i></i>
                    <?php echo $this->translate('Save changes'); ?></button>
            </div>
        </div>
    </div>

    <?php echo $this->form()->closeTag($form); ?>

</div>
