<div class="separator bottom"></div>
    <div class="heading-buttons">
        <h3 class="glyphicons settings"><?php echo $this->translate('Settings'); ?></h3>
    </div>
<div class="separator bottom"></div>

<div class="innerLR">
    <!-- Tabs -->
    <div class="widget widget-2 widget-tabs widget-tabs-2">
        <div class="widget-head">
            <ul>
                <li class="active"><a class="glyphicons flag" href="#countrySelection" data-toggle="tab">
                        <?php echo $this->translate('Active countries'); ?></a></li>
                <li><a class="glyphicons link" href="#countryLocale" data-toggle="tab">
                        <?php echo $this->translate('Country languages'); ?></a></li>
            </ul>
        </div>
        <div class="widget-body">
            <div class="tab-content">
                <div class="tab-pane active" id="countrySelection">
                    <?php $form = $this->form; ?>
                    <?php $form->setAttribute('class', 'form-horizontal margin-none')->prepare(); ?>

                    <?php echo $this->form()->openTag($form); ?>

                    <div class="widget-body col-md-12">
                        <div class="tab-content">
                            <div class="row">

                                <div class="col-md-10">
                                    <label><?php echo $this->translate('Country'); ?></label>
                                    <?php echo $this->formRow($form->get('country')); ?>
                                    <div class="separator bottom"></div>
                                </div>

                                <div class="col-md-2">
                                    <div class="separator"></div>
                                    <div class="form-group" style="padding-right: 15px;">
                                        <a type="button" class="btn btn-icon btn-primary glyphicons circle_ok pull-right"
                                           data-activateCountry data-href="<?php echo $this->url('settings/activateCountry'); ?>">
                                            <i></i><?php echo $this->translate('Activate country'); ?></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <?php echo $this->form()->closeTag($form); ?>

                    <div class="col-md-12">

                        <div class="separator"></div>

                        <h4><?php echo $this->translate('Active countries'); ?></h4>

                        <div class="activeCountries">
                        <?php if (!empty($this->activeCountries)) {
                            foreach ($this->activeCountries as $country) { ?>
                                <div class="col-md-3" id="activeCountry_<?php echo $country->getId(); ?>" style="padding: 0">
                                    <div class="widget-stats">
                                        <div class="col-md-8">
                                            <strong><?php echo $country->getName(); ?></strong>
                                        </div>
                                        <div class="col-md-4">
                                            <a class="btn btn-sm btn-primary"
                                               href="<?php echo $this->url('settings/editActiveCountry',
                                                array('id' => $country->getId())); ?>"><strong>Edit</strong></a>
                                            <a class="btn btn-sm btn-danger" href="#" data-deleteActiveCountry
                                               data-href="<?php echo $this->url('settings/deleteActiveCountry',
                                                   array('id' => $country->getId())); ?>"
                                               data-id="<?php echo $country->getId(); ?>"> <strong>Delete</strong></a>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                </div>
                            <?php } ?>
                        <?php } else { ?>
                            <div class="widget-body center activeCountryMessage">
                                <span class="gritter-add-regular btn btn-inverse btn-block">
                                    <?php echo $this->translate('No active countries found. Please set them.'); ?>
                                </span>
                            </div>
                        <?php } ?>
                        </div>

                    </div>
                </div>
                <div class="tab-pane" id="countryLocale">
                    <h5>Tab content #2</h5>
                    <p>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec id eros a orci adipiscing accumsan id eget sem. Etiam sit amet neque ligula, ac hendrerit metus. Phasellus convallis nulla nec leo dapibus sed feugiat felis feugiat. Nulla facilisi. Mauris quis tortor eu eros posuere tristique. In turpis leo, iaculis eget tincidunt in, gravida sit amet diam. Vivamus viverra, nisl vitae consectetur volutpat, ipsum risus tempor augue, in convallis leo massa in sem. Maecenas in urna quis purus pulvinar posuere. Fusce blandit viverra placerat. Fusce elementum turpis sed velit blandit elementum.</p>
                </div>
            </div>
        </div>
    </div>
    <!-- // Tabs END -->
</div>
