<?php echo $this->doctype(); ?>
<html>
<head>
    <meta charset="utf-8">

    <meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'>
    <!-- This line is best to remove and just send it as a http header -->
    <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no'>
    <!-- Required for Responsive Web Design -->
    <?php echo $this->headTitle($this->translate('MyUNHCR'))->setSeparator(' - ')->setAutoEscape(false) ?>
    <!-- Le styles -->
    <?php     echo $this->headLink()->prependStylesheet($this->basePath() . '/css/site.css'); ?>
    <?php echo $this->headScript(); ?>
</head>
<body>
<?php echo $this->content; ?>
</body>
</html>