<?php echo $this->doctype(); ?>
<html lang='en' class='no-js'>
<head>
  <meta charset='utf-8'> <!-- Charset should be defined as early as possible to avoid rendering problems -->

  <!-- ==== DNS Prefetch ==== -->
  <link rel="dns-prefetch" href="//maps.googleapis.com">

  <!-- ==== Critical Meta Tags ==== -->
  <meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'> <!-- This line is best to remove and just send it as a http header -->
  <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no'> <!-- Required for Responsive Web Design -->
  <?php echo $this->headTitle($this->translate('MyUNHCR'))->setSeparator(' - ')->setAutoEscape(false) ?>

  <!-- ======= Critical Inline Scripts ======= -->
  <script>

    var ua = navigator.userAgent.toLowerCase();
    var doc = document.documentElement;
    window.DOMContentLoaded = false;

    var featureTest = function() {
      // Show javascript support
      doc.className = doc.className.replace(/\bno-js\b/,'js');
    }

    // Log if DOMContentLoaded has fired, for scripts which load asynchronously after the event
    var logDOMContent = function() {
      document.addEventListener("DOMContentLoaded", function(){
        window.DOMContentLoaded = true;
      });
    }

    featureTest();
    logDOMContent();

  </script>

  <!-- ==== CSS ==== -->
  <?php
    $this->headLink()->appendStylesheet('/css/primitive.css');
    $this->headLink()->appendStylesheet('/css/modern.css');
    echo $this->headLink();
  ?>

  <!-- ==== Secondary Meta Tags ==== -->
  <meta name='description' content=''>
</head>
<body class="<?php echo $this->layout()->body_class; ?>">

<?php echo $this->content; ?>

<!-- Various helpers -->
<div id='screenSize'></div>
<div id='alertPolite'></div>
<div id='alertAssertive'></div>

<!-- Secondary script files (async!) -->
<script src='http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js' defer async></script>
<script src='scripts/main.js' defer async></script>

</body>
</html>
