<div id="menu" class="hidden-sm hidden-print">
    <div id="menuInner">
        <!-- Scrollable menu wrapper with Maximum height -->
        <div class="slim-scroll" data-scroll-height="420px">

            <div id="search">
                <input type="text" placeholder="Quick search ..." />
                <button class="glyphicons search"></button>
            </div>

            <?php echo $this->navigation('navigation')->menu(); ?>

        </div>
    </div>
</div>
