<?php if ($this->pageCount) { ?>
    <div class="innerLR">
    <!-- Previous page link -->
        <div class="separator top form-inline small">
            <ul class="pagination pagination-sm">
              <?php if (isset($this->previous)) { ?>
                <li>
                  <a href="<?php echo $this->url($this->route, $this->routeParams); ?>?
                  <?php echo http_build_query(array_merge($this->routeParams , array('page' => $this->previous))) ?>">
                    <<
                  </a>
                </li>
              <?php } else { ?>
                <li class="disabled">
                  <a href="#">
                    <<
                  </a>
                </li>
              <?php } ?>
              <!-- Numbered page links -->
              <?php foreach ($this->pagesInRange as $page) { ?>
                <?php if ($page != $this->current) { ?>
                <li>
                    <a href="<?php echo $this->url($this->route);?>?<?php echo http_build_query(array_merge($this->routeParams ,
                        array('page' => $page))); ?>">
                      <?php echo $page; ?>
                    </a>
                </li>
                <?php } else { ?>
                <li class="active">
                    <a href="#"><?php echo $page; ?></a>
                </li>
                <?php } ?>
              <?php } ?>

              <!-- Next page link -->
              <?php if (isset($this->next)) { ?>
                <li>
                  <a href="<?php echo $this->url($this->route); ?>?<?php echo  http_build_query(array_merge($this->routeParams ,
                      array('page' => $this->next)));?>">
                    >>
                  </a>
                </li>
              <?php } else { ?>
                <li class="disabled">
                  <a href="#">
                    >>
                  </a>
                </li>
              <?php } ?>
            </ul>
        </div>
    </div>

    <div class="clearfix"></div>
<?php } ?>

