<div class="navbar main hidden-print">

    <a href="#" class="appbrand">
            <span><?php echo $this->translate('MyUNHCR'); ?>
                <span><?php echo $this->translate('Administration'); ?></span>
            </span>
    </a>

    <ul class="topnav pull-right">
<!--        <li class="visible-lg">
            <ul class="notif">
                <li><a href="" class="glyphicons envelope" data-toggle="tooltip" data-placement="bottom"
                       data-original-title="5 new messages"> 5</a></li>
                <li><a href="" class="glyphicons shopping_cart" data-toggle="tooltip" data-placement="bottom"
                       data-original-title="1 new orders"> 1</a></li>
                <li><a href="" class="glyphicons log_book" data-toggle="tooltip" data-placement="bottom"
                       data-original-title="3 new activities"> 3</a></li>
            </ul>
        </li>
        <li class="dropdown visible-lg">
            <a href="" data-toggle="dropdown" class="glyphicons cogwheel">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu pull-right">
                <li><a href="">Some option</a></li>
                <li><a href="">Some other option</a></li>
                <li><a href="">Other option</a></li>
            </ul>
        </li>
        <li class="hidden-xs"><a href="#themer" data-toggle="collapse" class="glyphicons eyedropper">
                <span>Themer</span></a>
        </li>
        <li class="hidden-sm hidden-xs">
            <a href="" data-toggle="dropdown"><img src="../images/lang/en.png" alt="en" /></a>
            <ul class="dropdown-menu pull-right">
                <li class="active"><a href="#" title="English"><img src="../images/lang/en.png" alt="English"> English</a></li>
                <li><a href="#" title="Romanian"><img src="../images/lang/ro.png" alt="Romanian"> Romanian</a></li>
                <li><a href="#" title="Italian"><img src="../images/lang/it.png" alt="Italian"> Italian</a></li>
                <li><a href="#" title="French"><img src="../images/lang/fr.png" alt="French"> French</a></li>
                <li><a href="#" title="Polish"><img src="../images/lang/pl.png" alt="Polish"> Polish</a></li>
            </ul>
        </li>
-->

        <?php //use hasIdentity method to ensure that user is logged in; else return to login after acl check ?>
        <?php if ($this->auth->hasIdentity()) { ?>
            <li class="account">
                <a data-toggle="dropdown" href="#" class="glyphicons logout lock"><span class="hidden-sm text">
                        <?php echo $this->auth->getIdentity()->getEmail(); ?></span></a>
                <ul class="dropdown-menu pull-right">
    <!--                <li><a href="#" class="glyphicons cogwheel">Settings</a></li>
                                    <li><a href="#" class="glyphicons camera">My Photos</a></li>-->
                    <li class="highlight profile">
                            <span>
                                <span class="heading"><?php echo $this->translate('Profile '); ?>
                                    <a href="<?php echo $this->url('account'); ?>" class="pull-right">
                                        <?php echo $this->translate('Edit'); ?></a>
                                </span>
    <!--                            <span class="img"></span>-->
                                <span class="details">
                                    <a href="<?php echo $this->url('account'); ?>">
                                        <?php echo $this->auth->getIdentity()->getEmail(); ?></a>
                                </span>
                                <span class="clearfix"></span>
                            </span>
                    </li>
                    <li>
                            <span>
                                <a class="btn btn-default btn-small pull-right" style="padding: 2px 10px; background: #fff;"
                                   href="<?php echo $this->url('logout'); ?>"><?php echo $this->translate('Log Out'); ?></a>
                            </span>
                    </li>
                </ul>
            </li>
        <?php } ?>
    </ul>

</div>
