<div class="navbar main hidden-print">

    <a href="#" class="appbrand">
            <span><?php echo $this->translate('MyUNHCR'); ?>
                <span><?php echo $this->translate('Administration'); ?></span>
            </span>
    </a>

    <ul class="topnav pull-right">
<!--        <li class="visible-lg">
            <ul class="notif">
                <li><a href="" class="glyphicons envelope" data-toggle="tooltip" data-placement="bottom"
                       data-original-title="5 new messages"> 5</a></li>
                <li><a href="" class="glyphicons shopping_cart" data-toggle="tooltip" data-placement="bottom"
                       data-original-title="1 new orders"> 1</a></li>
                <li><a href="" class="glyphicons log_book" data-toggle="tooltip" data-placement="bottom"
                       data-original-title="3 new activities"> 3</a></li>
            </ul>
        </li>
        <li class="dropdown visible-lg">
            <a href="" data-toggle="dropdown" class="glyphicons cogwheel">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu pull-right">
                <li><a href="">Some option</a></li>
                <li><a href="">Some other option</a></li>
                <li><a href="">Other option</a></li>
            </ul>
        </li>
        <li class="hidden-xs"><a href="#themer" data-toggle="collapse" class="glyphicons eyedropper">
                <span>Themer</span></a>
        </li> -->
        <li class="hidden-sm hidden-xs">
            <?php if (isset($_SESSION['countrySettings'])) { ?>
                <a href="" data-toggle="dropdown" id="<?php echo $_SESSION['countrySettings']['countryId']; ?>"
                   data-activeCountry><?php echo $_SESSION['countrySettings']['countryName']; ?></a>
            <?php } else { ?>
                <a href="" data-toggle="dropdown" id="" data-activeCountry>
                   <?php echo $this->translate('Choose country'); ?> </a>
            <?php } ?>
            <ul class="dropdown-menu pull-right activeCountriesNav">
                <?php  foreach ($this->CountrySelection() as $country) { ?>
                    <li id="<?php echo $country->getId(); ?>">
                        <a href="#" data-href="<?php echo $this->url('countrySelection', array('id' => $country->getId())); ?>"
                           title="<?php echo $country->getName(); ?>" data-countrySelection><?php echo $country->getName(); ?></a>
                    </li>
                <?php } ?>
            </ul>
        </li>

        <?php //use hasIdentity method to ensure that user is logged in; else return to login after acl check ?>
        <?php if ($this->auth->hasIdentity()) { ?>
            <li class="account">
                <a data-toggle="dropdown" href="#" class="glyphicons logout lock"><span class="hidden-sm text">
                        <?php echo $this->auth->getIdentity()->getEmail(); ?></span></a>
                <ul class="dropdown-menu pull-right">
    <!--                <li><a href="#" class="glyphicons cogwheel">Settings</a></li>
                                    <li><a href="#" class="glyphicons camera">My Photos</a></li>-->
                    <li class="highlight profile">
                            <span>
                                <span class="heading"><?php echo $this->translate('Profile '); ?>
                                    <a href="<?php echo $this->url('account/profile'); ?>" class="pull-right">
                                        <?php echo $this->translate('Edit'); ?></a>
                                </span>
    <!--                            <span class="img"></span>-->
                                <span class="details">
                                    <a href="<?php echo $this->url('account/profile'); ?>">
                                        <?php echo $this->auth->getIdentity()->getEmail(); ?></a>
                                </span>
                                <span class="clearfix"></span>
                            </span>
                    </li>
                    <li>
                            <span>
                                <a class="btn btn-default btn-small pull-right" style="padding: 2px 10px; background: #fff;"
                                   href="<?php echo $this->url('logout'); ?>"><?php echo $this->translate('Log Out'); ?></a>
                            </span>
                    </li>
                </ul>
            </li>
        <?php } ?>
    </ul>

</div>
