
<?php $form = $this->form; ?>
<?php $form->setAttribute('class', 'form-signin'); ?>
<?php $form->setAttribute('action', $this->url('process', array('action' => 'authenticate'))); ?>
<?php $form->prepare(); ?>

<div id="login">

    <?php echo $this->form()->openTag($form); ?>

        <div class="widget widget-4">
            <div class="widget-head">
               <h4 class="heading"><?php echo $this->translate('Restricted area'); ?></h4>
            </div>
        </div>
        <h2 class="glyphicons unlock form-signin-heading"><i></i> <?php echo $this->translate('Please sign in'); ?></h2>
        <div class="uniformjs">
            <?php echo $this->formRow($form->get('email')); ?>
            <?php echo $this->formRow($form->get('password')); ?>
            <label class="checkbox">
                <?php echo $this->formRow($form->get('rememberMe')); ?><?php echo $this->translate('Remember me'); ?>
            </label>
        </div>

        <?php echo $this->formRow($form->get('submit')); ?>

    <?php echo $this->form()->closeTag($form); ?>

</div>


<?php
    if ($this->messages) {

        echo '<div class="alert alert-danger" style="margin-top: -50px;">';
        foreach($this->messages as $message) {
            echo $this->translate($message);
        }
        echo '</div>';
    }
?>
