<section class='page'>

  <div class='sectionHeader'>
    <div class='grid'>
      <div class='grid_column'>
        <div class='sectionHeader_inner'>
          <h1 class='sectionHeader_title'><?php echo $this->translate('Book an Appointment'); ?></h1>
          <div id='sectionInfo_trigger' class='sectionHeader_info' unselectable='on'><i class='icon -infoBlack24'></i></div>
        </div>
      </div>
    </div>

    <div id='sectionInfo' class='sectionHeader_info_wrapper' animate>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_info_body preformat'>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati molestiae quod modi consequatur quae aliquid, doloremque id praesentium, quia voluptate ratione repudiandae dicta, ipsum expedita?</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>
      <form action='book-an-appointment2.html' class='booking form' ajaxForm>

        <div class='form_item'>
          <label class='form_label' for='appointmentType'><?php echo $this->translate('What would you like to do at UNHCR ?'); ?></label>
          <div class='form_field customSelect'>
            <select class='formSelect customSelect_select -custom' id='appointmentType'>
              <option><?php echo $this->translate('Registration'); ?></option>
            </select>
            <a unselectable='on' class='customSelect_overlay'><?php echo $this->translate('Registration'); ?></a>
          </div>
        </div>

        <div class='form_item'>
          <label class='form_label' for='authentication'><?php echo $this->translate("Please enter your identification number:")?> (<?php echo $this->translate("optional")?>)</label>
          <div class='form_field'>
            <input class='formInput' type='text' name='' value='' placeholder='ID Number' id='authentication'>
          </div>
        </div>

        <div class='grid -compact -reverse'>
          <div class='grid_column -small7'>
            <input class='button -primary -fullWidth' type='submit' name='' value="<?php echo $this->translate('Next'); ?>">
          </div>
          <div class='grid_column -small5'>
            <a class='button -fullWidth' href='menu-page.html' ajaxNav><?php echo $this->translate('Cancel'); ?></a>
          </div>
        </div>

      </form>
    </div>
  </div>
</section>
