<div id='relay' bodyClass="<?php echo $this->layout()->body_class; ?>"></div>
<section class='page'>

  <div class='sectionHeader'>
    <div class='grid'>
      <div class='grid_column'>
        <div class='sectionHeader_inner'>
          <h1 class='sectionHeader_title'><?php echo $this->translate("Book an Appointment");?></h1>
          <div id='sectionInfo_trigger' class='sectionHeader_info' unselectable='on'><i class='icon -infoBlack24'></i></div>
        </div>
      </div>
    </div>

    <div id='sectionInfo' class='sectionHeader_info_wrapper' animate>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_info_body preformat'>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati molestiae quod modi consequatur quae aliquid, doloremque id praesentium, quia voluptate ratione repudiandae dicta, ipsum expedita?</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8 -static'>
      <form action='book-an-appointment3.html' class='booking form' ajaxForm>

        <div class='form_item'>
          <label class='form_label' for='date'><?php echo $this->translate("Please enter Date for Appointment:");?></label>
          <div class='form_item_help hide-for-js'>Example: 28/12/2014, or 28.12.2014</div>
          <div class='form_field'>
            <input class='formInput' type='date' placeholder='Day/Month/Year' inputDate>
          </div>
        </div>

        <div class='form_item'>
          <label class='form_label' for='time'><?php echo $this->translate("Please enter Time for Appointment:");?></label>
          <div class='form_item_help hide-for-js'>Example: 14:30</div>
          <div class='form_field'>
            <input class='formInput' type='time' placeholder='Hour:Minutes' inputTime>
          </div>
        </div>

        <div class='grid -compact -reverse'>
          <div class='grid_column -small7'>
            <input class='button -primary -fullWidth' type='submit' name='' value="<?php echo $this->translate('Book now'); ?>">
          </div>
          <div class='grid_column -small5'>
            <a class='button -fullWidth' href='book-an-appointment.html' ajaxNav><?php echo $this->translate('Back'); ?></a>
          </div>
        </div>

      </form>
    </div>
  </div>
</section>
