<section class='page'>

  <div class='sectionHeader'>
    <div class='grid'>
      <div class='grid_column'>
        <div class='sectionHeader_inner'>
          <h1 class='sectionHeader_title'><?php echo $this->translate("Book an Appointment");?></h1>
          <div id='sectionInfo_trigger' class='sectionHeader_info' unselectable='on'><i class='icon -infoBlack24'></i></div>
        </div>
      </div>
    </div>

    <div id='sectionInfo' class='sectionHeader_info_wrapper' animate>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_info_body preformat'>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati molestiae quod modi consequatur quae aliquid, doloremque id praesentium, quia voluptate ratione repudiandae dicta, ipsum expedita?</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>
      <form action='book-an-appointment2.html' class='booking form' ajaxForm>

        <div class='form_item'>
          <label class='form_label' for='appointmentType'>What would you like to do at UNHCR ?</label>
          <div class='form_field customSelect'>
            <select class='formSelect customSelect_select -custom' id='appointmentType'>
              <option>Registration</option>
            </select>
            <a unselectable='on' class='customSelect_overlay'>Registration</a>
          </div>
        </div>

        <div class='grid'>
          <div class='grid_column -small5'>
            <div class='form_item'>
              <a class='button -submit' href="refugee-feedback.html">Cancel</a>
            </div>
          </div>
          
          <div class='grid_column -small7'>
            <div class='form_item'>
              <input class='button -secondary -submit floatRight clearfix' type='submit' name='' value='Next'>
            </div>
          </div>
        </div>

      </form>
    </div>
  </div>
</section>