<section class='page'>

  <div class='sectionHeader'>
    <div class='grid'>
      <div class='grid_column'>
        <div class='sectionHeader_inner'>
          <h1 class='sectionHeader_title'>Book an Appointemnt</h1>
          <div id='sectionInfo_trigger' class='sectionHeader_info' unselectable='on'><i class='icon -infoBlack24'></i></div>
        </div>
      </div>
    </div>

    <div id='sectionInfo' class='sectionHeader_info_wrapper' animate>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_info_body preformat'>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati molestiae quod modi consequatur quae aliquid, doloremque id praesentium, quia voluptate ratione repudiandae dicta, ipsum expedita?</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>
      <form action='my-unhcr-services-menu.html' class='booking form'>

        <h2 class='form_legend'>Appointment will be booked for:</h2>

        <div class='form_item'>
          <div class='form_field'>
            <input class='formInput' type='date' name='' value='' placeholder='' disabled id='date'>
          </div>
        </div>

        <div class='form_item'>
          <div class='form_field'>
            <input class='formInput' type='time' name='' value='' placeholder='' disabled id='time'>
          </div>
        </div>

        <div class='sectionContent'>
          <p class='sectionContent_inner'>Press "Book" button to confirm your booking.</p>
        </div>

        <div class='grid'>
          <div class='grid_column -small5'>
            <div class='form_item'>
              <a class='button -submit' href="book-an-appointment3.html">Back</a>
            </div>
          </div>
          
          <div class='grid_column -small7'>
            <div class='form_item'>
              <input class='button -primary -submit floatRight clearfix' type='submit' name='' value='Book'>
            </div>
          </div>
        </div>

      </form>
    </div>
  </div>
</section>