<?php echo $this->partial('application/index/header.phtml');?>

<section class='page'>

  <div class='sectionHeader'>
    <div class='grid'>
      <div class='grid_column'>
        <div class='sectionHeader_inner'>
          <h1 class='sectionHeader_title'>Book an Appointemnt</h1>
          <abbr class='sectionHeader_info'
            title='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos iste consequuntur quia illum qui minima.'
            ><i class='icon -infoBlack24'></i></abbr>
        </div>
      </div>
    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>
      <form action='book-an-appointment3.html' class='booking form'>

        <div class='form_item'>
          <label class='form_label' for='date'>Please enter Date for Appointment:</label>
          <div class='form_field'>
            <input class='formInput' type='date' name='' value='' placeholder='' id='date'>
          </div>
        </div>

        <div class='form_item'>
          <label class='form_label' for='time'>Please enter Time for Appointment:</label>
          <div class='form_field'>
            <input class='formInput' type='time' name='' value='' placeholder='' id='time'>
          </div>
        </div>

        <div class='grid'>
          <div class='grid_column -small5'>
            <div class='form_item'>
              <a class='button -submit' href="book-an-appointment.html">Back</a>
            </div>
          </div>
          
          <div class='grid_column -small7'>
            <div class='form_item'>
              <input class='button -secondary -submit floatRight clearfix' type='submit' name='' value='Next'>
            </div>
          </div>
        </div>

      </form>
    </div>
  </div>
</section>

