<div id='relay' bodyClass="<?php echo $this->layout()->body_class; ?>"></div>
<section class='page'>

  <div class='sectionHeader'>
    <div class='sectionHeader_top'>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_top_inner'>
            <h1 class='sectionHeader_title'><?php echo $this->translate("Book an Appointment");?></h1>
            <div id='sectionInfo_trigger' class='sectionHeader_info' unselectable='on'><i class='icon -infoBlack24'></i></div>
          </div>
        </div>
      </div>
    </div>
    <div id='sectionInfo' class='sectionHeader_bottom' animate>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_description preformat'>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati molestiae quod modi consequatur quae aliquid, doloremque id praesentium, quia voluptate ratione repudiandae dicta, ipsum expedita?</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>

        <?php $form = $this->form; ?>
        <?php $form->setAttribute('class', 'booking form'); ?>
        <?php $form->setAttribute('action', $this->url('bookAnAppointment'))->prepare(); ?>

        <?php echo $this->form()->openTag($form); ?>

        <div class='form_item'>
            <label class='form_label' for='appointmentType'><?php echo $this->translate('What would you like to do at UNHCR ?'); ?></label>
            <div class='form_field customSelect'>
                <?php echo $this->formRow($this->form->get('appointmentType')); ?>
                <a unselectable='on' class='customSelect_overlay'><?php echo $this->translate($form->get('appointmentType')
                        ->getEmptyOption()); ?></a>
            </div>
        </div>

        <div class='form_item'>
            <label class='form_label' for='authentication'><?php echo $this->translate("Please enter your identification number:")?> (<?php echo $this->translate("optional")?>)</label>
            <div class='form_field'>
                <?php echo $this->formRow($this->form->get('authentification')); ?>
            </div>
        </div>

        <div class='grid -compact -reverse'>
            <div class='grid_column -small7'>
                <input class='button -primary -fullWidth' type='submit' value="<?php echo $this->translate('Next'); ?>">
            </div>
            <div class='grid_column -small5'>
                <a class='button -fullWidth' href='menu-page.html' ajaxNav tabindex='0'><?php echo $this->translate('Cancel'); ?></a>
            </div>
        </div>

        <?php echo $this->form()->closeTag($form); ?>

    </div>
  </div>
</section>
