<?php echo $this->partial('application/index/header.phtml');?>

<section class='page'>
  <div class='grid'>
    <div class='grid_column'>
      <h1 class='sectionTitle'>Book an Appointemnt</h1>
      <span class='tooltip'></span>
      
      <form action='book-an-appointment3.html' class='booking form'>
        
        <div class='grid'>
          <div class='grid_column -medium9 -mediumPlus8'>

            <div class='form_item'>
              <label class='form_label' for='date'>Choose Date of Appointment</label>
              <div class='form_field'>
                <input class='formInput' type='date' name='' value='' placeholder='' id='date'>
              </div>
            </div>

            <div class='form_item'>
              <label class='form_label' for='time'>Choose Time of Appointment</label>
              <div class='form_field'>
                <input class='formInput' type='time' name='' value='' placeholder='' id='time'>
              </div>
            </div>

            <div class='grid'>
              <div class='grid_column -small5'>
                <div class='form_item'>
                  <a class='button -submit' href="book-an-appointment.html">Back</a>
                </div>
              </div>
              
              <div class='grid_column -small7'>
                <div class='form_item'>
                  <input class='button -secondary -submit' type='submit' name='' value='Next'>
                </div>
              </div>
            </div>

          </div>
        </div><!-- /grid -->

      </form>
    </div>
  </div>
</section>

