<div id='relay' bodyClass="<?php echo $this->layout()->body_class; ?>"></div>
<section class='page'>

  <div class='sectionHeader'>
    <div class='grid'>
      <div class='grid_column'>
        <div class='sectionHeader_inner'>
          <h1 class='sectionHeader_title'><?php echo $this->translate("Check Your Status");?></h1>
          <div id='sectionInfo_trigger' class='sectionHeader_info' unselectable='on'><i class='icon -infoBlack24'></i></div>
        </div>
      </div>
    </div>

    <div id='sectionInfo' class='sectionHeader_info_wrapper' animate>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_info_body preformat'>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati molestiae quod modi consequatur quae aliquid, doloremque id praesentium, quia voluptate ratione repudiandae dicta, ipsum expedita?</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>
      
      <h2 class='pageTitle'>Your Asylum Application status:</h2>

      <!--
        Display only one of these below.
        Note: Only the class name changes (-positive, -negative, -unknown) so there's no need to keep three separate html blocks
      -->

      <div class='feedback -unknown gapSmall'>
        <i class='feedback_icon icon'></i>
        <h1 class='feedback_title'>Pending</h1>
        <div class='feedback_description preformat'>
          <p>Some useful information here lorem ipsum dolor sit amet minima <a>culpa eos cum</a> commodi officia minima.</p>
        </div>
      </div>

      <div class='feedback -positive gapSmall'>
        <i class='feedback_icon icon'></i>
        <h1 class='feedback_title'>Accepted</h1>
        <div class='feedback_description preformat'>
          <p>Some useful information here lorem ipsum dolor sit amet minima <a>culpa eos cum</a> commodi officia minima.</p>
        </div>
      </div>

      <div class='feedback -negative gapSmall'>
        <i class='feedback_icon icon'></i>
        <h1 class='feedback_title'>Rejected</h1>
        <div class='feedback_description preformat'>
          <p>Some useful information here lorem ipsum dolor sit amet minima <a>culpa eos cum</a> commodi officia minima.</p>
        </div>
      </div>

      <a href='menu-page.html' class='button -fullWidth'><?php echo $this->translate('Back to Homepage'); ?></a>
    </div>
  </div>

</section>