<?php echo $this->partial('application/index/header.phtml');?>

<section class='page'>
  <div class='grid'>
    <div class='grid_column'>
      <h1 class='sectionTitle'>Check Your Status</h1>
      <span class='tooltip'></span>

      <form action='my-unhcr-services-menu.html' class='survey form'>
        
        <div class='grid'>
          <div class='grid_column -medium9 -mediumPlus8'>

            <div class='form_item'>
              <label class='form_label' for='checkWhat'>Your Asylum-Application's status:</label>
              <p class='content_summary warningText'>Decision is pending</p>
            </div>

            <div class='grid'>
              <div class='grid_column -small5'>
                <div class='form_item'>
                  <a class='button -submit' href='check-your-status2.html'>Back</a>
                </div>
              </div>
              
              <div class='grid_column -small7'>
                <div class='form_item'>
                  <input class='button -primary -submit' type='submit' name='' value='OK'>
                </div>
              </div>
            </div>

          </div>
        </div><!-- /grid -->

      </form>
    </div>
  </div>
</section>

