<section class='page'>

  <div class='sectionHeader'>
    <div class='grid'>
      <div class='grid_column'>
        <div class='sectionHeader_inner'>
          <h1 class='sectionHeader_title'><?php echo $this->translate("Frequently Asked Questions");?></h1>
          <div id='sectionInfo_trigger' class='sectionHeader_info' unselectable='on'><i class='icon -infoBlack24'></i></div>
        </div>
      </div>
    </div>

    <div id='sectionInfo' class='sectionHeader_info_wrapper' animate>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_info_body preformat'>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati molestiae quod modi consequatur quae aliquid, doloremque id praesentium, quia voluptate ratione repudiandae dicta, ipsum expedita?</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>

      <div class='accordion'>
        <div id='accTab-1'>
          <a href='#accTab-1' class='button accTab'><?php echo $this->translate('What is MyUNHCR?'); ?></a>
          <div class='accContent'>
            <p>My UNHCR is not just a project, it is a Web Application, that everyone can use either on their Computer or Cellphone, old or new, it doesn't matter. Just start the site/app and get all informations you need.</p>
          </div>
        </div>
        <div id='accTab-2'>
          <a href='#accTab-2' class='button accTab'><?php echo $this->translate('How anonymous is this application ?'); ?></a>
          <div class='accContent'>
            <p>My UNHCR is not just a project, it is a Web Application, that everyone can use either on their Computer or Cellphone, old or new, it doesn't matter. Just start the site/app and get all informations you need.</p>
          </div>
        </div>
      </div>

    </div>
  </div>
</section>

