<section class='page'>

  <div class='sectionHeader'>
    <div class='grid'>
      <div class='grid_column'>
        <div class='sectionHeader_inner'>
          <h1 class='sectionHeader_title'>Frequently Asked Questions</h1>
          <abbr class='sectionHeader_info'
            title='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos iste consequuntur quia illum qui minima.'
            ><i class='icon -infoBlack24'></i></abbr>
        </div>
      </div>
    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>

      <div class='accordion'>
        <div id='accTab-1'>
          <a href='#accTab-1' class='button accTab'>What is MyUNHCR?</a>
          <div class='accContent'>
            <p>My UNHCR is not just a project, it is a Web Application, that everyone can use either on their Computer or Cellphone, old or new, it doesn't matter. Just start the site/app and get all informations you need.</p>
          </div>
        </div>
        <div id='accTab-2'>
          <a href='#accTab-2' class='button accTab'>How anonymous is this application ?</a>
          <div class='accContent'>
            <p>My UNHCR is not just a project, it is a Web Application, that everyone can use either on their Computer or Cellphone, old or new, it doesn't matter. Just start the site/app and get all informations you need.</p>
          </div>
        </div>
      </div>

    </div>
  </div>
</section>

