<section class='page'>

  <div class='sectionHeader'>
    <div class='grid'>
      <div class='grid_column'>
        <div class='sectionHeader_inner'>
          <h1 class='sectionHeader_title'>Frequently Asked Questions</h1>
          <abbr class='sectionHeader_info'
            title='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos iste consequuntur quia illum qui minima.'
            ><i class='icon -infoBlack24'></i></abbr>
        </div>
      </div>
    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>
      <div class='content'>
        <h2 class='contentTitle'>What is MyUNHCR?</h2>
        <p class='content_summary'>MyUNHCR is an App that not only refugees can use but everyone..</p>
      </div>

    </div>
  </div>
</section>