<div id='relay' bodyClass="<?php echo $this->layout()->body_class; ?>"></div>
<section class='page'>

  <div class='sectionHeader'>
    <div class='sectionHeader_top'>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_top_inner'>
            <h1 class='sectionHeader_title'><?php echo $this->translate("Frequently Asked Questions");?></h1>
            <div id='sectionInfo_trigger' class='sectionHeader_info' unselectable='on'><i class='icon -infoBlack24'></i></div>
          </div>
        </div>
      </div>
    </div>
    <div id='sectionInfo' class='sectionHeader_bottom' animate>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_description preformat'>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati molestiae quod modi consequatur quae aliquid, doloremque id praesentium, quia voluptate ratione repudiandae dicta, ipsum expedita?</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <?php if (count($this->faq) > 0) { ?>
      <ul class='faq' accordion>
          <?php foreach ($this->faq as $faq) { ?>
              <li class='faq_item' accordionItem animateOnReady tabindex='0'>
                  <div class='grid -clean'>
                      <div class='grid_column'>
                          <h2 class='faq_item_title'><?php echo $faq->getTitle(); ?></h2>

                          <div class='faq_item_description preformat -compact' autoHeight animateOnReady>
                              <?php echo $faq->getContent(); ?>
                          </div>
                      </div>
                  </div>
              </li>
          <?php } ?>
      </ul>
  <?php } else { ?>
    <div class='grid'>
      <div class='grid_column -medium9 -mediumPlus8'>
        <div class='feedback -unknown gapTopSmall'>
          <div class='feedback_description preformat'>
            <p><?php echo $this->translate('There are currently no frequently asked questions for this category.'); ?></p>
          </div>
        </div>
      </div>
    </div>
  <?php } ?>

</section>
