<?php echo $this->partial('application/index/header.phtml');?>
<section class='page'>
    <div class='row'>
        <div class='small-12 columns text-center margin-t10 margin-b10'>
            <h4>Refugee Feedback</h4>
        </div>
    </div>
    <div class='row'>
        <div class='small-12'>
            <ul class='bblock-list'>
                <li>
                    <a href='take-a-survey.html' title='Survey'>Take a Survey</a><i class='fa fa-angle-right'></i>
                </li>
                <li>
                    <a href='file-a-complaint.html' title='Complaint'>File a Complaint</a><i class='fa fa-angle-right'></i>
                </li>
                <li>
                    <a href='report-an-incident.html' title='Report an Incident'>Report an Incident</a
                        ><i class='fa fa-angle-right'></i>
                </li>
                <li>
                    <a href='faq-refugee.html' title='Map of Services'>FAQ</a><i class='fa fa-angle-right'></i>
                </li>
        </div>
    </div>
</section><!-- /page -->
<?php echo $this->partial('application/index/footer.phtml');?>