<section class='page'>

  <div class='sectionHeader'>
    <div class='grid'>
      <div class='grid_column'>
        <div class='sectionHeader_inner'>
          <h1 class='sectionHeader_title'><?php echo $this->translate("Your Feedback");?></h1>
          <div id='sectionInfo_trigger' class='sectionHeader_info' unselectable='on'><i class='icon -infoBlack24'></i></div>
        </div>
      </div>
    </div>

    <div id='sectionInfo' class='sectionHeader_info_wrapper' animate>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_info_body preformat'>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati molestiae quod modi consequatur quae aliquid, doloremque id praesentium, quia voluptate ratione repudiandae dicta, ipsum expedita?</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>
      <div class='sectionContent'>
        <p class='sectionContent_inner'>UNHCR encourages refugees to comment on the organization's performance in order to improve its services.<br><br><span class='warningText'>Important:&nbsp;</span>you can provide your feedback 
        anonymously if you choose to do so.</p>
      </div>

      <form action='refugee-feedback.html' class='feedback form' ajaxForm>
        <div class='form_item'>
          <label class='form_label' for='feedbackMessage'><?php echo $this->translate('Your Message'); ?></label>
          <div class='form_field'>
            <textarea class='formTextarea' id='feedbackMessage' placeholder='...'></textarea>
          </div>
        </div>

        <div class='form_item'>
          <input class='button -primary -submit floatRight clearfix' type='submit' name='' value='Send'>
        </div>
      </form>
      
    </div>
  </div>
</section>
