<div id='relay' bodyClass="<?php echo $this->layout()->body_class; ?>"></div>
<section class='page'>

  <div class='sectionHeader'>
    <div class='sectionHeader_top'>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_top_inner'>
            <h1 class='sectionHeader_title'><?php echo $this->translate("File a Complaint");?></h1>
            <div id='sectionInfo_trigger' class='sectionHeader_info' unselectable='on'><i class='icon -infoBlack24'></i></div>
          </div>
        </div>
      </div>
    </div>
    <div id='sectionInfo' class='sectionHeader_bottom' animate>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_description preformat'>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati molestiae quod modi consequatur quae aliquid, doloremque id praesentium, quia voluptate ratione repudiandae dicta, ipsum expedita?</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>
      
      <div class='preformat gap'>
        <p><?php echo $this->translate('UNHCR encourages refugees to comment on the organization\'s performance in order to improve its services.'); ?></p>
        <p><?php echo $this->translate("<b>Important:</b> You can provide your feedback anonymously if you choose to do so."); ?></p>
      </div>

        <?php $form = $this->form; ?>
        <?php $form->setAttribute('class', 'form'); ?>
        <?php $form->setAttribute('action', $this->url('fileAComplaint'))->prepare(); ?>

        <?php echo $this->form()->openTag($form); ?>

        <div class='form_item'>
            <label class='form_label' for='feedbackMessage'><?php echo $this->translate('Please describe the incident:'); ?></label>
            <div class='form_field'>
                <?php echo $this->formRow($form->get('feedbackMessage')); ?>
            </div>
        </div>

        <div class='grid -compact -reverse'>
            <div class='grid_column -small7'>
                <input class='button -primary -fullWidth' type='submit' value="<?php echo $this->translate('Next'); ?>">
            </div>
            <div class='grid_column -small5'>
                <a class='button -fullWidth' href='/menu-page.html' ajaxNav tabindex='0'><?php echo $this->translate('Cancel'); ?></a>
            </div>
        </div>

        <?php echo $this->form()->closeTag($form); ?>

    </div>
  </div>

</section>
