
<header id='header' class='mainHeader'>
  <div class='grid -clean -collapse -largeExpand'>
    <div class='grid_column'>
      <div class='mainHeader_wrapper'>
        <div class='mainHeader_top'>
          <a id='callTrigger' class='mainHeader_call' href='tel:01 2345 6789'>
            <img class='mainHeader_call_img h24' src='media/icons/phone-white-h24@2x.png' alt=''>
            <span class='mainHeader_call_label'> Call info</span>
          </a>
          <a class='mainHeader_logo' href='menu-page.html' ajaxNav>
            <img class='mainHeader_logo_img h42' src='media/icons/logo-white-h42@2x.png' alt='MyUNHCR'>
            <span class='mainHeader_logo_expanded'></span>
          </a>
          <a id='mobileMenuTrigger' class='mainHeader_menu' unselectable='on' href='menu-page.html' ajaxNav
            ><span class='mainHeader_menu_label'
              >Menu</span><i class='icon mainHeader_menu_icon mainHeader_menu_open'></i></a>
        </div>
        <div class='mainHeader_bottom'>
          <!-- <nav id='mobileMenuWrapper' class='mainHeader_nav'>
            <ul class='mainHeader_nav_list'>
              <li class='mainHeader_nav_item'><a class='mainHeader_nav_link' 
                href='refugee-feedback.html'>Feedback</a></li>
              <li class='mainHeader_nav_item'><a class='mainHeader_nav_link' 
                href='information-services-menu.html'>Information</a></li>
              <li class='mainHeader_nav_item'><a class='mainHeader_nav_link' 
                href='my-unhcr-services-menu.html'>MyUNHCR</a></li>
              <li class='mainHeader_nav_item'><a class='mainHeader_nav_link' href='settings.html'>Settings</a></li>
            </ul>
          </nav> -->
          <div class='mainHeader_infoLine'>
            <a class='mainHeader_infoLine_link' href='tel:01 2345 6789'>Info line: <b>+01 2345 6789</b></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>
