<header id='header' class='padding-t5 padding-b5'>
    <div class='row'>
        <div class='small-12 columns'>
            <div class='row'>
                <div class='small-3 columns header-logo text-center'>
                    <img src='/images/logo/logo_2.png' alt='UNHCR Logo'>
                </div>
                <div class='small-9 columns header-title padding-t5'>
                    <h3>Welcome to MyUNHCR</h3>
                </div>
            </div>
        </div>
    </div>
</header><!-- /header -->