<div id='relay' bodyClass="<?php echo $this->layout()->body_class; ?>"></div>
<section class='page'>
  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>
      <h1 class='welcomeTitle gap'><?php echo $this->translate('MyUNHCR'); ?></h1>
      <a class='welcomeLogo gap' href='settings.html' ajaxNav><img class='welcomeLogo_img' src='media/pages/welcome/welcome-logo.png' alt=''></a>
      <a class='button -primary -submit' href='settings.html' ajaxNav><?php echo $this->translate("Start");?></a>
    </div>
  </div>
</section>