<section class="page">
    <div class='row'>
        <div class='small-12 columns text-center margin-t30'>
            <h1 class='primary-color font-medium'>MyUNHCR</h1>
        </div>
    </div>

    <div class='row'>
        <div class='small-12 columns text-center margin-t30 padding-t20'>
            <img src='/images/logo/logo_1.png' alt='UNHCR Logo'>
        </div>
    </div>
</section>
<?php echo $this->partial('application/index/home-footer.phtml');?>