<div id='relay' bodyClass="<?php echo $this->layout()->body_class; ?>"></div>
<section class='page'>

  <div class='sectionHeader -clean'>
    <div class='sectionHeader_top'>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_top_inner'>
            <h1 class='sectionHeader_title'><?php echo $this->translate("List of Sectors");?></h1>
            <div id='sectionInfo_trigger' class='sectionHeader_info' unselectable='on'><i class='icon -infoBlack24'></i></div>
          </div>
        </div>
      </div>
    </div>
    <div id='sectionInfo' class='sectionHeader_bottom' animate>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_description preformat'>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati molestiae quod modi consequatur quae aliquid, doloremque id praesentium, quia voluptate ratione repudiandae dicta, ipsum expedita?</p>
          </div>
        </div>
      </div>
    </div>
    <form class='pageSearch form' id="sectorFilter" action='' method='post' ajaxForm>
      <div class='grid -clean'>
        <div class='grid_column -medium9 -mediumPlus8'>
          <div class='grid -clean -collapse'>
            <div class='grid_column -small8 -medium9'>
              <div class='form_item'>
                <div class='form_field'>
                  <input class='input formInput' id='searchField' type='text' value=''
                         placeholder='<?php echo $this->translate('Search...'); ?>' data-clearQuery>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>

    <?php if (count($this->sectors) > 0) { ?>
    <div class='activeSearch'>
    <div class='grid -clean'>
      <div class='grid_column -medium9 -mediumPlus8'>
        <div class='activeSearch_body'>
          <?php echo count($this->sectors) . $this->translate(' sectors totally'); ?>
            <a class='activeSearch_remove link' href="list-of-sectors.html"><?php echo $this->translate('Show all sectors'); ?></a>
        </div>
      </div>
    </div>
  </div>

  <ul class='sectorList'>
      <?php foreach ($this->sectors as $sector) { ?>
          <li class='orgList_item'>
              <div class='orgList_link'>
                  <span class='orgList_item_acronym'><?php echo $sector->getSectorAcronym(); ?></span>
                  <?php echo $sector->getSectorName(); ?>
              </div>
          </li>
      <?php } ?>
  </ul>
  <?php } else { ?>
    <div class="feedback -unknown gapTopSmall">
       <div class="feedback_description preformat">
           <h3><?php echo $this->translate('No sector data found.'); ?></h3>
       </div>
    </div>
    <?php } ?>
</section>
