<?php echo $this->partial('application/index/header.phtml');?>

<section class='page'>

  <div class='sectionHeader'>
    <div class='grid'>
      <div class='grid_column'>
        <div class='sectionHeader_inner'>
          <h1 class='sectionHeader_title'>List by Sector</h1>
          <abbr class='sectionHeader_info'
            title='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos iste consequuntur quia illum qui minima.'
            ><i class='icon -infoBlack24'></i></abbr>
        </div>
      </div>
    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>
      <form action='' class='form'>

        <div class='form_item'>
          <div class='form_field'>
            <input class='formInput' id='searchInput' type='text' placeholder='Search..'>
          </div>
        </div>

        <div class='form_item'>
          <div class='form_field customSelect'>
            <select class='formSelect -custom' id='selectSector'>
              <option>--</option>
            </select>
            <a unselectable='on' class='formSelect_overlay'>--</a>
          </div>
        </div>

      </form>
    </div>
  </div>
</section>

<?php echo $this->partial('application/index/footer.phtml');?>

