<div id='relay' bodyClass="<?php echo $this->layout()->body_class; ?>"></div>
<section class='page'>

  <div class='sectionHeader -clean'>
    <div class='sectionHeader_top'>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_top_inner'>
            <h1 class='sectionHeader_title'><?php echo $this->translate("List by Sector");?></h1>
            <div id='sectionInfo_trigger' class='sectionHeader_info' unselectable='on'><i class='icon -infoBlack24'></i></div>
          </div>
        </div>
      </div>
    </div>
    <div id='sectionInfo' class='sectionHeader_bottom' animate>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_description preformat'>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati molestiae quod modi consequatur quae aliquid, doloremque id praesentium, quia voluptate ratione repudiandae dicta, ipsum expedita?</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='mapHeader'>
    <div class='grid -clean'>
      <div class='grid_column -medium9 -mediumPlus8'>
        <form action='' class='form' ajaxForm>
          <div class='form_item'>
            <div class='grid -clean -collapse'>
              <div class='grid_column -small9 mapHeader_search_left'>
                <div class='form_field customSelect'>
                    <input class='formInput' id='searchInput' type='text' placeholder='Search..'>
                </div>
              </div>
            </div>
          </div>
        </form>

    <div class='grid'>
      <div class='grid_column -medium9 -mediumPlus8 sectorSearch' data-url="<?php echo $this->url('listBySector'); ?>">
        <p>Type for search</p>
      </div>
    </div>
  </div>

  </div>

</section>
