<div id='relay' bodyClass="<?php echo $this->layout()->body_class; ?>"></div>
<section class='page'>

  <div class='sectionHeader -clean'>
    <div class='sectionHeader_top'>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_top_inner'>
            <h1 class='sectionHeader_title'><?php echo $this->translate("List of Organizations");?></h1>
            <div id='sectionInfo_trigger' class='sectionHeader_info' unselectable='on'><i class='icon -infoBlack24'></i></div>
          </div>
        </div>
      </div>
    </div>
    <div id='sectionInfo' class='sectionHeader_bottom' animate>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_description preformat'>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati molestiae quod modi consequatur quae aliquid, doloremque id praesentium, quia voluptate ratione repudiandae dicta, ipsum expedita?</p>
          </div>
        </div>
      </div>
    </div>
    <?php $form = $this->form; ?>
    <form class='pageSearch form' action='<?php echo $this->url('listOfOrganizations') ?>' method='post' ajaxForm>
      <div class='grid -clean'>
        <div class='grid_column -medium9 -mediumPlus8'>
          <div class='grid -clean -collapse'>
            <div class='grid_column -small8 -medium9'>
              <div class='form_item <?php if (isset($form->getMessages()['feedbackMessage'])) echo '-error'; ?>'>
                <div class='form_field'>
                  <input class='pageSearch_input formInput' id='searchField' type='text' value='Health' placeholder='<?php echo $this->translate('Search...'); ?>' data-clearQuery>
                </div>
              </div>
            </div>
            <div class='grid_column -small4 -medium3 mapHeader_search_right'>
              <input class='pageSearch_submit button -fullWidth' type='submit' value='<?php echo $this->translate('Filter'); ?>' data-geocode>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>

  <div class='activeSearch'>
    <div class='grid -clean'>
      <div class='grid_column -medium9 -mediumPlus8'>
        <div class='activeSearch_body'>
          4 results for "Health" <a class='activeSearch_remove link'>Show all organizations</a>
        </div>
      </div>
    </div>
  </div>

  <ul class='orgList'>
    <li class='orgList_item'>
      <a class='orgList_link' data-ripple
        href='organization-details.html'
        ajaxNav tabindex='0'><span class='orgList_item_acronym'>DRC</span> Danish Refugee Council
      </a>
    </li>
    <li class='orgList_item'>
      <a class='orgList_link' data-ripple
        href='organization-details.html'
        ajaxNav tabindex='0'><span class='orgList_item_acronym'>JHAS</span> Jordan Health Aid
      </a>
    </li>
    <li class='orgList_item'>
      <a class='orgList_link' data-ripple
        href='organization-details.html'
        ajaxNav tabindex='0'><span class='orgList_item_acronym'>SCI</span> Save the Children
      </a>
    </li>
    <li class='orgList_item'>
      <a class='orgList_link' data-ripple
        href='organization-details.html'
        ajaxNav tabindex='0'><span class='orgList_item_acronym'>WFP</span> World Food Programme
      </a>
    </li>
  </ul>


  <div class='grid'>
      <div class='grid_column -medium9 -mediumPlus8'>

          <?php if (isset($this->organizationData)) {  $organizationData = $this->organizationData; ?>
              <div class='preformat gap'>
                  <h5><?php echo $this->translate('Name'); ?></h5> <?php echo $organizationData->getOrganizationName(); ?><br/>
                  <h5><?php echo $this->translate('Acronym'); ?></h5> <?php echo $organizationData->getOrganizationAcronym(); ?><br/>
                  <h5><?php echo $this->translate('Url'); ?></h5> <?php echo $organizationData->getOrganizationUrl(); ?><br/>
                  <h5><?php echo $this->translate('Description'); ?></h5> <?php echo $organizationData->getDescription(); ?><br/>
                  <h5><?php echo $this->translate('Address'); ?></h5> <?php echo $organizationData->getOrganizationAddress(); ?><br/>
                  <h5><?php echo $this->translate('Email'); ?></h5> <?php echo $organizationData->getOrganizationEmail(); ?><br/>
                  <h5><?php echo $this->translate('Phone'); ?></h5> <?php echo $organizationData->getOrganizationPhone(); ?><br/>
                  <h5><?php echo $this->translate('Opening hours'); ?></h5> <?php echo $organizationData->getOrganizationOpeningHours(); ?>
              </div>
          <?php } ?>
      </div>
  </div>

</section>
