<div id='relay' bodyClass="<?php echo $this->layout()->body_class; ?>"></div>
<section class='page'>

  <div class='sectionHeader -clean'>
    <div class='sectionHeader_top'>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_top_inner'>
            <h1 class='sectionHeader_title'><?php echo $this->translate("List by Organization");?></h1>
            <div id='sectionInfo_trigger' class='sectionHeader_info' unselectable='on'><i class='icon -infoBlack24'></i></div>
          </div>
        </div>
      </div>
    </div>
    <div id='sectionInfo' class='sectionHeader_bottom' animate>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_description preformat'>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati molestiae quod modi consequatur quae aliquid, doloremque id praesentium, quia voluptate ratione repudiandae dicta, ipsum expedita?</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='mapHeader'>
    <div class='grid -clean'>
      <div class='grid_column -medium9 -mediumPlus8'>
          <?php $form = $this->form; ?>
          <form action='<?php echo $this->url('listOfOrganizations') ?>' method="post" class='form' ajaxForm>
          <div class='form_item <?php if (isset($form->getMessages()['feedbackMessage'])) echo '-error'; ?>'>
          <label class='form_label' for='feedbackMessage'><?php echo $this->translate('Choose organization:'); ?></label>
            <div class='grid -clean -collapse'>
              <div class='grid_column -small9 mapHeader_search_left'>
                <div class='form_field customSelect'>
                    <?php echo $this->formRow($form->get('organization')); ?>
                  <a class='customSelect_overlay' unselectable='on'>
                      <?php echo isset($this->organizationData) ?
                          $this->organizationData->getOrganizationName() :
                          $this->translate($form->get('organization')->getEmptyOption()); ?></a>
                </div>
              </div>
              <div class='grid_column -small3 mapHeader_search_right'>
                <input class='button -primary -fullWidth' type='submit' value='<?php echo $this->translate('Filter'); ?>' data-geocode>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>

  <div class='grid'>
      <div class='grid_column -medium9 -mediumPlus8'>
          <?php if (isset($this->organizationData)) {  $organizationData = $this->organizationData; ?>
              <div class='preformat gap'>
                  <h5><?php echo $this->translate('Name'); ?></h5> <?php echo $organizationData->getOrganizationName(); ?><br/>
                  <h5><?php echo $this->translate('Acronym'); ?></h5> <?php echo $organizationData->getOrganizationAcronym(); ?><br/>
                  <h5><?php echo $this->translate('Url'); ?></h5> <?php echo $organizationData->getOrganizationUrl(); ?><br/>
                  <h5><?php echo $this->translate('Description'); ?></h5> <?php echo $organizationData->getDescription(); ?><br/>
                  <h5><?php echo $this->translate('Address'); ?></h5> <?php echo $organizationData->getOrganizationAddress(); ?><br/>
                  <h5><?php echo $this->translate('Email'); ?></h5> <?php echo $organizationData->getOrganizationEmail(); ?><br/>
                  <h5><?php echo $this->translate('Phone'); ?></h5> <?php echo $organizationData->getOrganizationPhone(); ?><br/>
                  <h5><?php echo $this->translate('Opening hours'); ?></h5> <?php echo $organizationData->getOrganizationOpeningHours(); ?>
              </div>
          <?php } ?>
      </div>
  </div>

</section>
