<?php echo $this->partial('application/index/header.phtml');?>

<section class='page'>
  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>
      <h1 class='sectionTitle'>List by Sector</h1>
      <span class='tooltip'></span>

      <form action='' class='form'>

        <div class='form_item'>
          <div class='grid -collapse'>
            <div class='grid_column'>
              <div class='form_field'>
                <input class='formInput' id='searchInput' type='text' placeholder='Search..'>
              </div>
            </div>
          </div>
        </div>

        <div class='form_item'>
          <div class='grid -collapse'>
            <div class='grid_column'>
              <div class='form_field customSelect'>
                <select class='formSelect -custom' id='selectSector'>
                  <option>--</option>
                </select>
                <a unselectable='on' class='formSelect_overlay'>--</a>
              </div>
            </div>
          </div>
        </div>

      </form>
    </div>
  </div>
</section>

<?php echo $this->partial('application/index/footer.phtml');?>

