<div id='relay' bodyClass="<?php echo $this->layout()->body_class; ?>"></div>
<section class='page'>

  <div class='sectionHeader'>
    <div class='sectionHeader_top'>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_top_inner'>
            <h1 class='sectionHeader_title'><?php echo $this->translate("Map of Services");?></h1>
            <div id='sectionInfo_trigger' class='sectionHeader_info' unselectable='on'><i class='icon -infoBlack24'></i></div>
          </div>
        </div>
      </div>
    </div>
    <div id='sectionInfo' class='sectionHeader_bottom' animate>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_description preformat'>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati molestiae quod modi consequatur quae aliquid, doloremque id praesentium, quia voluptate ratione repudiandae dicta, ipsum expedita?</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>
      <form action='' class='form' ajaxForm>
        
        <div class='form_item'>
          <label class='form_label' for='location'><?php echo $this->translate('Where:'); ?></label>
          <div class='form_field'>
            <!-- Map to pin point with fallback to input ?  - check map-of-service.phtml -->
            <input class='formInput' type='text' name='' value='' placeholder='Location Address' id='location'>
          </div>
        </div>

      </form>
    </div>
  </div>

  <div class='grid -collapse'>
    <div class='grid_column -medium9 -mediumPlus8'>
      <div id='map' class='mapContainer -fill' data-openStreetMap data-href='<?php echo $this->url('getAjaxMarkers'); ?>'></div>
    </div>
  </div>

</section>
