<?php echo $this->partial('application/index/header.phtml');?>

<section class='page'>
  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>
      <h1 class='sectionTitle'>Services Available</h1>
      <span class='tooltip'></span>

      <div class='form_item'>
        <label class='form_label' for='location'>Where</label>
        <div class='form_field'>
          <!-- Map to pin point with fallback to input ?  - check map-of-service.phtml -->
          <input class='formInput' type='text' name='' value='' placeholder='Location Address' id='location'>
        </div>
      </div>

    </div>
  </div>
</section>

<?php echo $this->partial('application/index/footer.phtml');?>

