<?php echo $this->partial('application/index/header.phtml');?>

<section class='page'>
  <div class='grid'>
    <div class='grid_column'>
      <div class="grid">
    
        <div class='grid_column -medium6'>
          <a class='button -secondaryOutline -submit'
            href='information-services-menu.html' title='Information Services'>Information Services</a>
        </div>
        
        <div class='grid_column -medium6'>
          <a class='button -secondaryOutline -submit' 
            href='refugee-feedback.html' title='Refugee Feedback'>Refugee Feedback</a>
        </div>
        
        <div class='grid_column -medium6'>
          <a class='button -secondaryOutline -submit' 
            href='myUNHCR-services-menu.html' title='My UNHCR Services'>My UNHCR Services</a>
        </div>

        <div class='grid_column -medium6'>
          <a class='button -secondaryOutline -submit' 
            href='settings.html' title='Settings'>Settings</a>
        </div>

      </div>
    </div>
  </div>
</section>

<?php echo $this->partial('application/index/footer.phtml');?>

