<?php echo $this->partial('application/index/header.phtml');?>
    <section class="page">
        <div class='row'>
            <div class='small-12 columns text-center margin-t10 margin-b10'>
                <h4>Mu UNHCR Services</h4>
            </div>
        </div>
        <div class='row'>
            <div class='small-12'>
                <ul class="bblock-list">
                    <li>
                        <a href='book-an-appointment.html' title='Book an Appointment'>Book an Appointment</a
                            ><i class='fa fa-angle-right'></i>
                    </li>
                    <li>
                        <a href='check-your-status.html' title='Check Your Status'>Check Your Status</a
                            ><i class='fa fa-angle-right'></i>
                    </li>
                    <li>
                        <a href='update-personal-data.html' title='Update Personal Data'>Update Personal Data</a
                            ><i class='fa fa-angle-right'></i>
                    </li>
                    <li><a href='faq-myunhcr.html' title='Frequently Asked Questions'>FAQ</a><i class='fa fa-angle-right'></i></li>
                </ul>
            </div>
        </div>
    </section><!-- /page -->
<?php echo $this->partial('application/index/footer.phtml');?>