<nav class='fullNav grid -collapse -clean -largeExpand'>
  <div class='grid_column -large4 gapSmall'>
    <ul class='sitemap'>
      <li class='sitemap_group'>
        <h2 class='sitemap_group_title'>Feedback</h2>
        <ul class='linkGroup'>
          <li class='linkGroup_item'>
            <a class='linkGroup_link ajaxNavigation' href='report-an-incident.html'>Report an Incident</a>
          </li>
          <li class='linkGroup_item'>
            <a class='linkGroup_link ajaxNavigation' href='take-a-survey.html'>Take a Survey</a>
          </li>
          <li class='linkGroup_item'>
            <a class='linkGroup_link ajaxNavigation' href='faq.html'>FAQ</a>
          </li>
        </ul>
      </li>
    </ul>
  </div>

  <div class='grid_column -large4 gapSmall'>
    <ul class='sitemap'>
      <li class='sitemap_group'>
        <h2 class='sitemap_group_title'>Information</h2>
        <ul class='linkGroup'>
          <li class='linkGroup_item'>
            <a class='linkGroup_link ajaxNavigation' href='news-and-events.html'>News and Events</a>
          </li>
          <li class='linkGroup_item'>
            <a class='linkGroup_link ajaxNavigation' href='map-of-service.html'>Map of Services</a>
          </li>
          <li class='linkGroup_item'>
            <a class='linkGroup_link ajaxNavigation' href='list-of-organizations.html'>List by Organization</a>
          </li>
          <li class='linkGroup_item'>
            <a class='linkGroup_link ajaxNavigation' href='list-by-sector.html'>List by Sector</a>
          </li>
          <li class='linkGroup_item'>
            <a class='linkGroup_link ajaxNavigation' href='faq-refugee.html'>FAQ</a>
          </li>
        </ul>
      </li>
    </ul>
  </div>

  <div class='grid_column -large4'>
    <ul class='sitemap'>
      <li class='sitemap_group'>
        <h2 class='sitemap_group_title'>MyUNHCR</h2>
        <ul class='linkGroup'>
          <li class='linkGroup_item'>
            <a class='linkGroup_link ajaxNavigation' href='book-an-appointment.html'>Book an Appointment</a>
          </li>
          <li class='linkGroup_item'>
            <a class='linkGroup_link ajaxNavigation' href='check-your-status.html'>Check Your Status</a>
          </li>
          <li class='linkGroup_item'>
            <a class='linkGroup_link ajaxNavigation' href='update-personal-data.html'>Update Personal Data</a>
          </li>
          <li class='linkGroup_item'>
            <a class='linkGroup_link ajaxNavigation' href='settings.html'>Update Settings</a>
          </li>
          <li class='linkGroup_item'>
            <a class='linkGroup_link ajaxNavigation' href='faq-myunhcr.html'>FAQ</a>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</nav>