<nav class='fullNav grid -collapse -clean -medium9 -mediumPlus8 -large12 -largeExpand'>
  <div class='grid_column -large4 gapSmall'>
    <ul class='menu'>
      <li class='menu_group'>
        <h2 class='menu_group_title'><?php echo $this->translate("Feedback");?></h2>
        <ul class='linkGroup'>
          <li class='linkGroup_item'>
            <a class='linkGroup_link' data-ripple
              href='report-an-incident.html'
              ajaxNav tabindex='0'><?php echo $this->translate("Report an Incident");?></a>
          </li>
          <li class='linkGroup_item'>
            <a class='linkGroup_link' data-ripple
              href='take-a-survey.html'
              ajaxNav tabindex='0'><?php echo $this->translate("Take a Survey");?></a>
          </li>
          <li class='linkGroup_item'>
            <a class='linkGroup_link' data-ripple
              href='file-a-complaint.html'
              ajaxNav tabindex='0'><?php echo $this->translate("File a Complaint");?></a>
          </li>
          <li class='linkGroup_item'>
            <a class='linkGroup_link' data-ripple
              href='faq-refugee.html'
              ajaxNav tabindex='0'><?php echo $this->translate("FAQ");?></a>
          </li>
        </ul>
      </li>
    </ul>
  </div>

  <div class='grid_column -large4 gapSmall'>
    <ul class='menu'>
      <li class='menu_group'>
        <h2 class='menu_group_title'><?php echo $this->translate("Information");?></h2>
        <ul class='linkGroup'>
          <li class='linkGroup_item'>
            <a class='linkGroup_link' data-ripple
              href='news-and-events.html'
              ajaxNav tabindex='0'><?php echo $this->translate("News and Events");?></a>
          </li>
          <li class='linkGroup_item'>
            <a class='linkGroup_link' data-ripple
              href='map-of-service.html'
              ajaxNav tabindex='0'><?php echo $this->translate("Map of Services");?></a>
          </li>
          <li class='linkGroup_item'>
            <a class='linkGroup_link' data-ripple
              href='list-of-organizations.html'
              ajaxNav tabindex='0'><?php echo $this->translate("List of Organizations");?></a>
          </li>
          <li class='linkGroup_item'>
            <a class='linkGroup_link' data-ripple
              href='list-of-sectors.html'
              ajaxNav tabindex='0'><?php echo $this->translate("List of Sectors");?></a>
          </li>
          <li class='linkGroup_item'>
            <a class='linkGroup_link' data-ripple
              href='faq.html'
              ajaxNav tabindex='0'><?php echo $this->translate("FAQ");?></a>
          </li>
        </ul>
      </li>
    </ul>
  </div>

  <div class='grid_column -large4'>
    <ul class='menu'>
      <li class='menu_group'>
        <h2 class='menu_group_title'><?php echo $this->translate("MyUNHCR");?></h2>
        <ul class='linkGroup'>
          <li class='linkGroup_item'>
            <a class='linkGroup_link' data-ripple
              href='book-an-appointment.html'
              ajaxNav tabindex='0'><?php echo $this->translate("Book an Appointment");?></a>
          </li>
          <li class='linkGroup_item'>
            <a class='linkGroup_link' data-ripple
              href='check-your-status.html'
              ajaxNav tabindex='0'><?php echo $this->translate("Check Your Status");?></a>
          </li>
          <li class='linkGroup_item'>
            <a class='linkGroup_link' data-ripple
              href='update-personal-data.html'
              ajaxNav tabindex='0'><?php echo $this->translate("Update Personal Data");?></a>
          </li>
          <li class='linkGroup_item'>
            <a class='linkGroup_link' data-ripple
              href='settings.html'
              ajaxNav tabindex='0'><?php echo $this->translate("Update Settings");?></a>
          </li>
          <li class='linkGroup_item'>
            <a class='linkGroup_link' data-ripple
              href='faq-myunhcr.html'
              ajaxNav tabindex='0'><?php echo $this->translate("FAQ");?></a>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</nav>
