<nav class='fullNav grid -collapse -clean -largeExpand'>
  <div class='grid_column -large4 gapSmall'>
    <ul class='sitemap'>
      <li class='sitemap_group'>
        <h2 class='sitemap_group_title'><?php echo $this->translate("Feedback");?></h2>
        <ul class='linkGroup'>
          <li class='linkGroup_item'>
            <a class='linkGroup_link'
              href='report-an-incident.html'
              ajaxNav='<?php echo $this->translate("Report an Incident");?>'
              ><?php echo $this->translate("Report an Incident");?></a>
          </li>
          <li class='linkGroup_item'>
            <a class='linkGroup_link'
              href='take-a-survey.html'
              ajaxNav='<?php echo $this->translate("Take a Survey");?>'
              ><?php echo $this->translate("Take a Survey");?></a>
          </li>
          <li class='linkGroup_item'>
            <a class='linkGroup_link'
              href='faq-refugee.html'
              ajaxNav='<?php echo $this->translate("FAQ");?>'
              ><?php echo $this->translate("FAQ");?></a>
          </li>
        </ul>
      </li>
    </ul>
  </div>

  <div class='grid_column -large4 gapSmall'>
    <ul class='sitemap'>
      <li class='sitemap_group'>
        <h2 class='sitemap_group_title'><?php echo $this->translate("Information");?></h2>
        <ul class='linkGroup'>
          <li class='linkGroup_item'>
            <a class='linkGroup_link'
              href='news-and-events.html'
              ajaxNav='<?php echo $this->translate("News and Events");?>'
              ><?php echo $this->translate("News and Events");?></a>
          </li>
          <li class='linkGroup_item'>
            <a class='linkGroup_link'
              href='map-of-service.html'
              ajaxNav='<?php echo $this->translate("Map of Services");?>'
              ><?php echo $this->translate("Map of Services");?></a>
          </li>
          <li class='linkGroup_item'>
            <a class='linkGroup_link'
              href='list-of-organizations.html'
              ajaxNav='<?php echo $this->translate("List by Organization");?>'
              ><?php echo $this->translate("List by Organization");?></a>
          </li>
          <li class='linkGroup_item'>
            <a class='linkGroup_link'
              href='list-by-sector.html'
              ajaxNav='<?php echo $this->translate("List by Sector");?>'
              ><?php echo $this->translate("List by Sector");?></a>
          </li>
          <li class='linkGroup_item'>
            <a class='linkGroup_link'
              href='faq.html'
              ajaxNav='<?php echo $this->translate("FAQ");?>'
              ><?php echo $this->translate("FAQ");?></a>
          </li>
        </ul>
      </li>
    </ul>
  </div>

  <div class='grid_column -large4'>
    <ul class='sitemap'>
      <li class='sitemap_group'>
        <h2 class='sitemap_group_title'><?php echo $this->translate("MyUNHCR");?></h2>
        <ul class='linkGroup'>
          <li class='linkGroup_item'>
            <a class='linkGroup_link'
              href='book-an-appointment.html'
              ajaxNav='<?php echo $this->translate("Book an Appointment");?>'
              ><?php echo $this->translate("Book an Appointment");?></a>
          </li>
          <li class='linkGroup_item'>
            <a class='linkGroup_link'
              href='check-your-status.html'
              ajaxNav='<?php echo $this->translate("Check Your Status");?>'
              ><?php echo $this->translate("Check Your Status");?></a>
          </li>
          <li class='linkGroup_item'>
            <a class='linkGroup_link'
              href='update-personal-data.html'
              ajaxNav='<?php echo $this->translate("Update Personal Data");?>'
              ><?php echo $this->translate("Update Personal Data");?></a>
          </li>
          <li class='linkGroup_item'>
            <a class='linkGroup_link'
              href='settings.html'
              ajaxNav='<?php echo $this->translate("Update Settings");?>'
              ><?php echo $this->translate("Update Settings");?></a>
          </li>
          <li class='linkGroup_item'>
            <a class='linkGroup_link'
              href='faq-myunhcr.html'
              ajaxNav='<?php echo $this->translate("FAQ");?>'
              ><?php echo $this->translate("FAQ");?></a>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</nav>