<section class='page'>

  <div class='sectionHeader'>
    <div class='grid'>
      <div class='grid_column'>
        <div class='sectionHeader_inner'>
          <h1 class='sectionHeader_title'>News and Events</h1>
          <abbr class='sectionHeader_info'
            title='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos iste consequuntur quia illum qui minima.'
            ><i class='icon -infoBlack24'></i></abbr>
        </div>
      </div>
    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>
      <form action='' class='form'>

        <div class='form_item'>
          <div class='form_field'>
            <input class='formInput' id='searchField' type='text' placeholder='Search..'>
          </div>
        </div>

      </form>

      <div class='news -newsSeperator'>
        <h2 class='news_title'><a href='news-article.html'>Refugee Camp in Jordan Open</a></h2>
        <p class='news_release'>Source:&nbsp;Google News<span class='news_date floatRight clearfix'
          >05/11/2014</span></p>
        <p class='news_description'>Lorem refugee Camp is now open for new arrivals into Jordan...</p>
      </div>

    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>
      <div class='form_item'>
        <a class='button -submit' href='menu-page.html'>Back</a>
      </div>
    </div>
  </div>
</section>

