<section class='page'>

  <div class='sectionHeader'>
    <div class='grid'>
      <div class='grid_column'>
        <div class='sectionHeader_inner'>
          <h1 class='sectionHeader_title'><?php echo $this->translate("News and Events");?></h1>
          <div id='sectionInfo_trigger' class='sectionHeader_info' unselectable='on'><i class='icon -infoBlack24'></i></div>
        </div>
      </div>
    </div>

    <div id='sectionInfo' class='sectionHeader_info_wrapper' animate>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_info_body preformat'>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati molestiae quod modi consequatur quae aliquid, doloremque id praesentium, quia voluptate ratione repudiandae dicta, ipsum expedita?</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>
      <form action='' class='form'>

        <div class='form_item'>
          <div class='form_field'>
            <input class='formInput' id='searchField' type='text' placeholder='Search..'>
          </div>
        </div>

      </form>

      <div class='news -newsSeperator'>
        <h2 class='news_title'><a href='news-article.html'><?php echo $this->translate('Refugee Camp in Jordan Open'); ?></a></h2>
        <p class='news_release'>Source:&nbsp;Google News<span class='news_date floatRight clearfix'
          >05/11/2014</span></p>
        <p class='news_description'>Lorem refugee Camp is now open for new arrivals into Jordan...</p>
      </div>

    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>
      <div class='form_item'>
        <a class='button -submit' href='menu-page.html'><?php echo $this->translate('Back'); ?></a>
      </div>
    </div>
  </div>
</section>

