<div id='relay' bodyClass="<?php echo $this->layout()->body_class; ?>"></div>
<section class='page'>

  <div class='sectionHeader'>
    <div class='sectionHeader_top'>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_top_inner'>
            <div class='sectionCategory'>
              <a class='sectionCategory_link' href='/list-of-organizations.html' ajaxNav><?php echo $this->translate("List of Organizations");?></a>
            </div>
            <h1 class='sectionHeader_title'>Danish Refugee Council (DRC)</h1>
          </div>
        </div>
      </div>
    </div>
    <div id='sectionInfo' class='sectionHeader_bottom' animate>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_description preformat'>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati molestiae quod modi consequatur quae aliquid, doloremque id praesentium, quia voluptate ratione repudiandae dicta, ipsum expedita?</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='organisation gap'>
    <div class='grid -clean'>
      <div class='grid_column -mediumPlus10'>
        <div class='grid -clean -reverse'>
          <div class='grid_column -medium6 -mediumPlus5'>
            <dl class='organisation_info definitionList'>
              <dt>Address</dt>
              <dd>Some Address 13<br>City Lorem</dd>
              <dt>Website</dt>
              <dd><a class='link' href='http://www.example.com' target='_blank'>www.example.com</a></dd>
              <dt>Email</dt>
              <dd><a class='link' href='mailto:organisation@example.com'>organisation@example.com</a></dd>
              <dt>Phone</dt>
              <dd><a class='link' href='tel:0123456789'>0123456789</a></dd>
              <dt>Opening hours</dt>
              <dd>08:00 GMT</dd>
            </dl>
          </div>
          <div class='grid_column -medium6 -mediumPlus7'>
            <div class='organisation_description preformat'>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis officia enim excepturi voluptatibus animi ad!</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='relatedServices sectionDivider'>
    <div class='grid -clean'>
      <div class='grid_column -mediumPlus10'>
        fdfds
      </div>
    </div>
  </div>

</section>
