<div id='relay' bodyClass="<?php echo $this->layout()->body_class; ?>"></div>
<section class='page'>

  <div class='sectionHeader'>
    <div class='sectionHeader_top'>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_top_inner'>
            <div class='sectionCategory'>
              <a class='sectionCategory_link' href='/list-of-organizations.html' ajaxNav>
                  <?php echo $this->translate("Organization");?></a>
            </div>
            <h1 class='sectionHeader_title'>
                <?php echo $this->organization->getOrganizationName() . ' (' . $this->organization->getOrganizationAcronym() . ')'; ?>
            </h1>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='organisation gap'>
    <div class='grid -clean'>
      <div class='grid_column -mediumPlus10'>
        <div class='grid -reverse'>
          <div class='grid_column -medium6 -mediumPlus5'>
            <dl class='organisation_info definitionList'>
              <?php if ($this->organization->getOrganizationAddress() != '') { ?>
                  <dt><?php echo $this->translate('Address'); ?></dt>
                  <dd><?php echo $this->organization->getOrganizationAddress(); ?></dd>
              <?php } ?>
              <?php if ($this->organization->getOrganizationUrl() != '') { ?>
                <dt><?php echo $this->translate('Website'); ?></dt>
                <dd><a class='link' href='<?php echo $this->organization->getOrganizationUrl(); ?>'
                     target='_blank'><?php echo $this->organization->getOrganizationUrl(); ?></a></dd>
              <?php } ?>
              <?php if ($this->organization->getOrganizationEmail() != '') { ?>
                <dt><?php echo $this->translate('Email'); ?></dt>
                <dd><a class='link' href='mailto:<?php echo $this->organization->getOrganizationEmail(); ?>'>
                      <?php echo $this->organization->getOrganizationEmail(); ?></a></dd>
              <?php } ?>
              <?php if ($this->organization->getOrganizationPhone() != '') { ?>
                <dt><?php echo $this->translate('Phone'); ?></dt>
                <dd><a class='link' href='tel:<?php echo $this->organization->getOrganizationPhone(); ?>'>
                      <?php echo $this->organization->getOrganizationPhone(); ?></a></dd>
              <?php } ?>
              <?php if ($this->organization->getOrganizationOpeningHours() != '') { ?>
                <dt><?php echo $this->translate('Opening hours'); ?></dt>
                <dd><?php echo $this->organization->getOrganizationOpeningHours(); ?></dd>
              <?php } ?>
            </dl>
          </div>
          <div class='grid_column -medium6 -mediumPlus7'>
            <div class='organisation_description preformat'>
              <p><?php echo $this->organization->getDescription(); ?></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='relatedServices sectionSeparator'>
    <div class='grid -clean'>
      <div class='grid_column -mediumPlus10'>
        <h2 class='pageTitle'><?php echo $this->translate('Related services'); ?></h2>
          <?php if (count($this->services) > 0) { ?>
        <ul class='serviceList'>
          <?php foreach ($this->services as $service) { ?>
              <li class='serviceList_item service'>
                  <h3 class='service_name'><?php echo $service->getServiceName() . ' (' . $service->getServiceAcronym() . ')'; ?></h3>
                  <a class='service_url link' href='<?php echo $service->getServiceUrl(); ?>' target='_blank'>
                      <?php echo $service->getServiceUrl(); ?></a><br>
                  <dl class='service_info definitionList -compact'>
                      <dt><?php echo $this->translate('Sector'); ?></dt>
                      <dd><?php echo $service->getSector()->getSectorName() . ' (' . $service->getSector()->getSectorAcronym() . ')'; ?></dd>
                  </dl>
              </li>
          <?php } ?>
        </ul>
          <?php } else { ?>
              <h3><?php echo $this->translate('No related services available'); ?></h3>
          <?php } ?>
      </div>
    </div>
  </div>

</section>
