<?php echo $this->partial('application/index/header.phtml');?>

<section class='page'>
  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>
      <h1 class='sectionTitle'>Refugee Feedback</h1>

      <ul class='serviceList'>
        <li><a href='take-a-survey.html' title='Take a Survey'>Take a Survey</a
          ><i class='fa fa-angle-right'></i></li>
          <!-- Feedback will not be in use ? -->
          <!-- <li><a href='file-a-complaint.html' title='Your Feedback'>Your Feedback</a
          ><i class='fa fa-angle-right'></i></li> -->
        <li><a href='report-an-incident.html' title='Report an Incident'>Report an Incident</a
          ><i class='fa fa-angle-right'></i></li>
        <li><a href='faq.html' title='Frequently Asked Questions'>FAQ</a
          ><i class='fa fa-angle-right'></i></li>
      </ul>

    </div>
  </div>
</section>

<?php echo $this->partial('application/index/footer.phtml');?>

