<div id='relay' bodyClass="<?php echo $this->layout()->body_class; ?>"></div>
<section class='page'>

  <div class='sectionHeader'>
    <div class='sectionHeader_top'>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_top_inner'>
            <h1 class='sectionHeader_title'><?php echo $this->translate("Report an Incident");?></h1>
            <div id='sectionInfo_trigger' class='sectionHeader_info' unselectable='on'><i class='icon -infoBlack24'></i></div>
          </div>
        </div>
      </div>
    </div>
    <div id='sectionInfo' class='sectionHeader_bottom' animate>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_description preformat'>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati molestiae quod modi consequatur quae aliquid, doloremque id praesentium, quia voluptate ratione repudiandae dicta, ipsum expedita?</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>
      <form action='report-an-incident2.html' class='incident form' ajaxForm>

        <div class='form_item'>
          <label class='form_label' for=''><?php echo $this->translate('Is this report Anonymous ?'); ?></label>
          <div class='grid -collapse -clean'>
            <div class='grid_column -small6 form_subitem'>
              <div class='bigRadio'>
                <input class='bigRadio_input' type='radio' name='anonymous' value='yes' id='anonymous-yes'>
                <label class='bigRadio_label' for='anonymous-yes'>Yes</label>
              </div>
            </div>
            <div class='grid_column -small6 form_subitem'>
              <div class='bigRadio'>
                <input class='bigRadio_input' type='radio' name='anonymous' value='no' id='anonymous-no'>
                <label class='bigRadio_label' for='anonymous-no'>No</label>
              </div>
            </div>
          </div>
        </div>

        <div class='form_item'>
          <label class='form_label' for='incidentCategory'><?php echo $this->translate('Category of the Incident:'); ?></label>
          <div class='form_field customSelect'>
            <select class='formSelect customSelect_select -custom' id='incidentCategory'>
              <option><?php echo $this->translate('Protection Incident'); ?></option>
            </select>
            <a unselectable='on' class='customSelect_overlay'><?php echo $this->translate('Protection Incident'); ?></a>
          </div>
        </div>

        <div class='form_item'>
          <label class='form_label' for='protectionType'><?php echo $this->translate('Which type of protection incident?'); ?></label>
          <div class='form_field customSelect'>
            <select class='formSelect customSelect_select -custom' id='protectionType'>
              <option><?php echo $this->translate('I don\'t know'); ?></option>
            </select>
            <a unselectable='on' class='customSelect_overlay'><?php echo $this->translate('I don\'t know'); ?></a>
          </div>
        </div>

        <div class='grid -compact -reverse'>
          <div class='grid_column -small7'>
            <input class='button -primary -fullWidth' type='submit' name='' value='Next'>
          </div>
          <div class='grid_column -small5'>
            <a class='button -fullWidth' href='menu-page.html' ajaxNav tabindex='0'><?php echo $this->translate('Cancel'); ?></a>
          </div>
        </div>

      </form>
    </div>
  </div>
</section>
