<?php echo $this->partial('application/index/header.phtml');?>

<section class='page'>

  <div class='sectionHeader'>
    <div class='grid'>
      <div class='grid_column'>
        <div class='sectionHeader_inner'>
          <h1 class='sectionHeader_title'>Report an Incident</h1>
          <abbr class='sectionHeader_info'
            title='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos iste consequuntur quia illum qui minima.'
            ><i class='icon -infoBlack24'></i></abbr>
        </div>
      </div>
    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>
      <form action='refugee-feedback.html' class='incident form'>

        <div class='form_item'>
          <label class='form_label' for='feedbackMessage'
            >Would you like to take/upload a picture of the incident ?</label>
          <div class='form_field'>
            <input type='file' accept='image/*;capture=camera'>
          </div>
        </div>

        <div class='form_item'>
          <label class='form_label' for='feedbackMessage'
            >Would you like to record your testimony of the incident ?</label>
          <div class='form_field'>
            <input type='file' accept='audio/*;capture=microphone'>
          </div>
        </div>

        <div class='grid'>
          <div class='grid_column -small5'>
            <div class='form_item'>
              <a class='button -submit' href="report-an-incident3.html">Back</a>
            </div>
          </div>
          
          <div class='grid_column -small7'>
            <div class='form_item'>
              <input class='button -primary -submit floatRight clearfix' type='submit' name='' value='Send'>
            </div>
          </div>
        </div>

      </form>
    </div>
  </div>
</section>

