<section class='page'>

  <div class='sectionHeader'>
    <div class='grid -clean'>
      <div class='grid_column'>
        <div class='sectionHeader_inner'>
          <h1 class='sectionHeader_title'>Report an Incident</h1>
          <div id='sectionInfo_trigger' class='sectionHeader_info' unselectable='on'><i class='icon -infoBlack24'></i></div>
        </div>
      </div>
    </div>

    <div id='sectionInfo' class='sectionHeader_info_wrapper' animate>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_info_body preformat'>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati molestiae quod modi consequatur quae aliquid, doloremque id praesentium, quia voluptate ratione repudiandae dicta, ipsum expedita?</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>
      <form action='report-an-incident2.html' class='incident form'>

        <div class='form_item'>
          <label class='form_label' for=''>Is this report Anonymous ?</label>
          <div class='grid -collapse -clean'>
            <div class='grid_column -small6 form_subitem'>
              <div class='bigRadio'>
                <input class='bigRadio_input' type='radio' name='anonymous' value='yes' id='anonymous-yes'>
                <label class='bigRadio_label' for='anonymous-yes'>Yes</label>
              </div>
            </div>
            <div class='grid_column -small6 form_subitem'>
              <div class='bigRadio'>
                <input class='bigRadio_input' type='radio' name='anonymous' value='no' id='anonymous-no'>
                <label class='bigRadio_label' for='anonymous-no'>No</label>
              </div>
            </div>
          </div>
        </div>

        <div class='form_item'>
          <label class='form_label' for='incidentCategory'>Category of the Incident:</label>
          <div class='form_field customSelect'>
            <select class='formSelect customSelect_select -custom' id='incidentCategory'>
              <option>Protection Incident</option>
            </select>
            <a unselectable='on' class='customSelect_overlay'>Protection Incident</a>
          </div>
        </div>

        <div class='form_item'>
          <label class='form_label' for='protectionType'>Which type of protection incident?</label>
          <div class='form_field customSelect'>
            <select class='formSelect customSelect_select -custom' id='protectionType'>
              <option>I don't know</option>
            </select>
            <a unselectable='on' class='customSelect_overlay'>I don't know</a>
          </div>
        </div>

        <div class='grid -compact -reverse'>
          <div class='grid_column -small7'>
            <input class='button -primary -fullWidth' type='submit' name='' value='Next'>
          </div>
          <div class='grid_column -small5'>
            <a class='button -fullWidth' href='menu-page.html' ajaxNav>Cancel</a>
          </div>
        </div>

      </form>
    </div>
  </div>
</section>