<section class='page'>

  <div class='sectionHeader'>
    <div class='grid'>
      <div class='grid_column'>
        <div class='sectionHeader_inner'>
          <h1 class='sectionHeader_title'>Report an Incident</h1>
          <abbr class='sectionHeader_info'
            title='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos iste consequuntur quia illum qui minima.'
            ><i class='icon -infoBlack24'></i></abbr>
        </div>
      </div>
    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>
      <form action='report-an-incident4.html' class='incident form'>

        <div class='form_item'>
          <label class='form_label' for='feedbackMessage'>Please describe the incident:</label>
          <div class='form_field'>
            <textarea class='formTextarea' id='feedbackMessage'></textarea>
          </div>
        </div>

        <div class='grid -compact -reverse'>
          <div class='grid_column -small7'>
            <input class='button -primary -fullWidth' type='submit' name='' value='Next'>
          </div>
          <div class='grid_column -small5'>
            <a class='button -fullWidth' href="report-an-incident2.html">Back</a>
          </div>
        </div>

      </form>
    </div>
  </div>
</section>