<div id='relay' bodyClass="<?php echo $this->layout()->body_class; ?>"></div>
<section class='page'>

  <div class='sectionHeader'>
    <div class='sectionHeader_top'>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_top_inner'>
            <h1 class='sectionHeader_title'><?php echo $this->translate("Report an Incident");?></h1>
            <div id='sectionInfo_trigger' class='sectionHeader_info' unselectable='on'><i class='icon -infoBlack24'></i></div>
          </div>
        </div>
      </div>
    </div>
    <div id='sectionInfo' class='sectionHeader_bottom' animate>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_description preformat'>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati molestiae quod modi consequatur quae aliquid, doloremque id praesentium, quia voluptate ratione repudiandae dicta, ipsum expedita?</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>
      <form action='report-an-incident3.html' class='incident form' ajaxForm>

        <h2 class='form_legend'><?php echo $this->translate('Where did this happen?'); ?></h2>

        <div class='form_item'>
          <label class='form_label' for='report_country'><?php echo $this->translate('Country'); ?></label>
          <div class='form_field customSelect'>
            <select class='formSelect customSelect_select -custom' id='report_country'>
              <option>(Autodetect)</option>
            </select>
            <a unselectable='on' class='customSelect_overlay'>(Autodetect)</a>
          </div>
        </div>

        <div class='form_item'>
          <label class='form_label' for='report_location'><?php echo $this->translate('Location'); ?></label>
          <div class='form_field'>
            <input class='formInput' type='text' name='' value='' placeholder='Location Address' id='report_location'>
          </div>
        </div>

        <div class='grid -compact -reverse'>
          <div class='grid_column -small7'>
            <input class='button -primary -fullWidth' type='submit' name='' value='Next'>
          </div>
          <div class='grid_column -small5'>
            <a class='button -fullWidth' href='report-an-incident.html' ajaxNav tabindex='0'><?php echo $this->translate('Back'); ?></a>
          </div>
        </div>

      </form>
    </div>
  </div>
</section>
