<?php echo $this->partial('application/index/header.phtml');?>

<section class='page'>

  <div class='sectionHeader'>
    <div class='grid'>
      <div class='grid_column'>
        <div class='sectionHeader_inner'>
          <h1 class='sectionHeader_title'>Report an Incident</h1>
          <abbr class='sectionHeader_info'
            title='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos iste consequuntur quia illum qui minima.'
            ><i class='icon -infoBlack24'></i></abbr>
        </div>
      </div>
    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>
      <form action='report-an-incident3.html' class='incident form'>

        <h2 class='form_legend'>Where did this happen?</h2>

        <div class='form_item'>
          <label class='form_label' for='report_country'>Country</label>
          <div class='form_field customSelect'>
            <select class='formSelect customSelect_select -custom' id='report_country'>
              <option>(Autodetect)</option>
            </select>
            <a unselectable='on' class='customSelect_overlay'>(Autodetect)</a>
          </div>
        </div>

        <div class='form_item'>
          <label class='form_label' for='report_location'>Location</label>
          <div class='form_field'>
            <input class='formInput' type='text' name='' value='' placeholder='Location Address' id='report_location'>
          </div>
        </div>

        <div class='grid -compact -reverse'>
          <div class='grid_column -small7'>
            <input class='button -primary -fullWidth' type='submit' name='' value='Next'>
          </div>
          <div class='grid_column -small5'>
            <a class='button -fullWidth' href="report-an-incident.html">Back</a>
          </div>
        </div>

      </form>
    </div>
  </div>
</section>

