<div id='relay' bodyClass="<?php echo $this->layout()->body_class; ?>"></div>
<section class='page'>

  <div class='sectionHeader'>
    <div class='grid'>
      <div class='grid_column'>
        <div class='sectionHeader_inner'>
          <h1 class='sectionHeader_title'><?php echo $this->translate("Report an Incident");?></h1>
          <div id='sectionInfo_trigger' class='sectionHeader_info' unselectable='on'><i class='icon -infoBlack24'></i></div>
        </div>
      </div>
    </div>

    <div id='sectionInfo' class='sectionHeader_info_wrapper' animate>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_info_body preformat'>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati molestiae quod modi consequatur quae aliquid, doloremque id praesentium, quia voluptate ratione repudiandae dicta, ipsum expedita?</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>
      <div class='feedback -positive gapSmall'>
        <i class='feedback_icon icon'></i>
        <h1 class='feedback_title'><?php echo $this->translate('Your report has been sent!'); ?></h1>
        <div class='feedback_description preformat'>
          <p>Some useful information here lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt rem asperiores at quisquam officiis praesentium!</p>
        </div>
      </div>
      <a href='menu-page.html' class='button -fullWidth'><?php echo $this->translate('Back to Homepage'); ?></a>
    </div>
  </div>
</section>
