<?php echo $this->partial('application/index/header.phtml');?>

<section class='page'>

  <div class='sectionHeader'>
    <div class='grid'>
      <div class='grid_column'>
        <div class='sectionHeader_inner'>
          <h1 class='sectionHeader_title'>Report an Incident</h1>
          <abbr class='sectionHeader_info'
            title='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos iste consequuntur quia illum qui minima.'
            ><i class='icon -infoBlack24'></i></abbr>
        </div>
      </div>
    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>
      
      <div class='feedback -positive gapSmall'>
        <i class='feedback_icon icon'></i>
        <h1 class='feedback_title'>Your report has been sent!</h1>
        <div class='feedback_description preformat'>
          <p>Some useful information here lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt rem asperiores at quisquam officiis praesentium!</p>
        </div>
      </div>

      <a href='menu-page.html' class='button -secondary -fullWidth'>Back to Homepage</a>

    </div>
  </div>
</section>

