<div id='relay' bodyClass="<?php echo $this->layout()->body_class; ?>"></div>
<section class='page'>

  <div class='sectionHeader'>
    <div class='sectionHeader_top'>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_top_inner'>
            <div class='sectionCategory'>
              <a class='sectionCategory_link' href='/list-of-sectors.html' ajaxNav><?php echo $this->translate("Sector");?></a>
            </div>
            <h1 class='sectionHeader_title'>Sector Name Here (DRC)</h1>
          </div>
        </div>
      </div>
    </div>
    <div id='sectionInfo' class='sectionHeader_bottom' animate>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_description preformat'>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati molestiae quod modi consequatur quae aliquid, doloremque id praesentium, quia voluptate ratione repudiandae dicta, ipsum expedita?</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='sector gap'>
    <div class='grid -clean'>
      <div class='grid_column -mediumPlus10'>
        <div class='organisation_description preformat'>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis officia enim excepturi voluptatibus animi ad!</p>
        </div>
      </div>
    </div>
  </div>

  <div class='relatedServices sectionSeparator'>
    <div class='grid -clean'>
      <div class='grid_column -mediumPlus10'>
        <h2 class='pageTitle'>Related services</h2>
        <ul class='serviceList'>
          <li class='serviceList_item service'>
            <h3 class='service_name'>Service name (ACRO)</h3>
            <a class='service_url link' href='http://www.example.com' target='_blank'>www.example.com</a><br>
            <dl class='service_info definitionList -compact'>
              <dt>Organization</dt>
              <dd><a class='link -neutral' href='organization-details.html' ajaxNav>Organization Name (ACRO)</a></dd>
            </dl>
          </li>
          <li class='serviceList_item service'>
            <h3 class='service_name'>Service name (ACRO)</h3>
            <a class='service_url link' href='http://www.example.com' target='_blank'>www.example.com</a><br>
            <dl class='service_info definitionList -compact'>
              <dt>Organization</dt>
              <dd><a class='link -neutral' href='organization-details.html' ajaxNav>Organization Name (ACRO)</a></dd>
            </dl>
          </li>
          <li class='serviceList_item service'>
            <h3 class='service_name'>Service name (ACRO)</h3>
            <a class='service_url link' href='http://www.example.com' target='_blank'>www.example.com</a><br>
            <dl class='service_info definitionList -compact'>
              <dt>Organization</dt>
              <dd><a class='link -neutral' href='organization-details.html' ajaxNav>Organization Name (ACRO)</a></dd>
            </dl>
          </li>
        </ul>
      </div>
    </div>
  </div>

</section>