<?php echo $this->partial('application/index/header.phtml');?>

<section class='page'>
  <div class='grid'>
    <div class='grid_column'>
      <h1 class='sectionTitle gap'>Settings</h1>
      <form action='' class='settings form'>
        
        <div class='form_item'>
          <label class='form_label' for='demoField1'>Basic input</label>
          <div class='form_field'>
            <input class="formInput" id='demoField1' type='text' placeholder='Basic input'>
          </div>
        </div>

        <div class='form_item'>
          <label class='form_label' for='demoField2'>Select</label>
          <div class='form_field customSelect'>
            <select class='formSelect -custom' id='demoField2'>
              <option>--</option>
              <option>Lorem ipsum</option>
              <option>Dolor sit amet</option>
            </select>
            <a unselectable='on' class='formSelect_overlay'>--</a>
          </div>
        </div>

        <div class='form_item'>
          <label class='form_label' for='demoField3'>Textarea</label>
          <div class='form_field'>
            <textarea class='formTextarea' id='demoField3' placeholder='Lorem ipsum...'></textarea>
          </div>
        </div>

      </form>
    </div>
  </div>
</section>