<?php $this->headLink()->appendStylesheet('/css/styleguide.css'); ?>

<div id='relay' bodyClass="<?php echo $this->layout()->body_class; ?>"></div>
<section class='page'>

  <div class='sectionHeader'>
    <div class='sectionHeader_top'>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_top_inner'>
            <h1 class='sectionHeader_title'><?php echo $this->translate("Styleguide");?></h1>
            <div id='sectionInfo_trigger' class='sectionHeader_info' unselectable='on'><i class='icon -infoBlack24'></i></div>
          </div>
        </div>
      </div>
    </div>
    <div id='sectionInfo' class='sectionHeader_bottom' animate>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_description preformat'>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati molestiae quod modi consequatur quae aliquid, doloremque id praesentium, quia voluptate ratione repudiandae dicta, ipsum expedita?</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='grid'>
    <div class='grid_column'>
      <h1 class='sectionTitle'><?php echo $this->translate('Page Title'); ?></h1>
    </div>
  </div>
  <div class='grid gap'>
    <div class='grid_column -medium6'>
      <div class='preformat gapSmall'>
        <h2>Morning 1 2 3 Evening</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur id rhoncus ante, vel luctus leo. Quisque et eros laoreet, pellentesque urna nec, tristique sem.</p>
      </div>
      <a class='button -primary'>Primary</a>
      <a class='button -secondary'>Secondary</a>
      <a class='button'>Neutral</a>
    </div>
    <div class='grid_column -medium6'>
      <div class='preformat gapSmall'>
        <h2>Morning 4 5 6 Evening</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur id rhoncus ante, vel luctus leo. Quisque et eros laoreet, pellentesque urna nec, tristique sem.</p>
      </div>
      <a class='button'>Neutral 1</a>
      <a class='button'>Neutral 2</a>
      <a class='button'>Neutral 3</a>
    </div>
  </div>
  <div class='grid gapLarge' lang='ar' dir='rtl'>
    <div class='grid_column -medium6 arabicSans'>
      <div class='preformat gapSmall'>
        <h2>الصباح 1 2 3 مساء</h2>
        <p>فقد ان واستسلم الفرنسي, وفي ألماني الفرنسية عل, في انه ٢٠٠٤ المشترك. بـ نفس طائرات الولايات, الأجل الدنمارك ستالينجراد تم يتم, فصل أم إنطلاق للألمان. لان اتفاق وتزويده الروسية ان, و وعلى إتفاقية بلا.</p>
      </div>
      <a class='button -primary'>ابتدائي</a>
      <a class='button -secondary'>ثانوي</a>
      <a class='button'>محايد</a>
    </div>
    <div class='grid_column -medium6'>
      <div class='preformat gapSmall'>
        <h2>الصباح 4 5 6 مساء</h2>
        <p>فقد ان واستسلم الفرنسي, وفي ألماني الفرنسية عل, في انه ٢٠٠٤ المشترك. بـ نفس طائرات الولايات, الأجل الدنمارك ستالينجراد تم يتم, فصل أم إنطلاق للألمان. لان اتفاق وتزويده الروسية ان, و وعلى إتفاقية بلا.</p>
      </div>
      <a class='button'>محايد 1</a>
      <a class='button'>محايد 2</a>
      <a class='button'>محايد 3</a>
    </div>
  </div>

  <div id='frontend' class='gapLarge'>
    <div class='grid'>
      <div class='grid_column'>
        <h1 class='sectionTitle'>Guidelines (draft)</h1>
        <div class='preformat'>
          <ul>
            <li>Primary (green) buttons should be used only once per page, for the most important call-to-action</li>
            <li>Always default to neutral button colors, use secondary (blue) theme only if you really have to</li>
            <li>Icon sizes are based on <b>height</b> of the icon, and include the following: 16px, 24px, 32px, 48px, 64px</li>
            <li>If you need just a plain simple horizontal margin or padding somewhere, consider using the <code>&amp;nbsp;</code> space character. It works with right-to-left languages with no additional adjustments.</li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div id='grid' class='gapLarge'>
    <div class='grid gapSmall'>
      <div class='grid_column'>
        <div class='demo'><span>grid_column</span></div>
      </div>
    </div>
    <div class='grid gapSmall'>
      <div class='grid_column -small6'>
        <div class='demo'><span>-small6</span></div>
      </div>
      <div class='grid_column -small6'>
        <div class='demo'><span>-small6</span></div>
      </div>
    </div>
    <div class='grid gapSmall'>
      <div class='grid_column -small3'>
        <div class='demo'><span>-small3</span></div>
      </div>
      <div class='grid_column -small3'>
        <div class='demo'><span>-small3</span></div>
      </div>
      <div class='grid_column -small3'>
        <div class='demo'><span>-small3</span></div>
      </div>
      <div class='grid_column -small3'>
        <div class='demo'><span>-small3</span></div>
      </div>
    </div>
    <div class='grid gapSmall'>
      <div class='grid_column -medium2'>
        <div class='demo'><span>-medium2</span></div>
      </div>
      <div class='grid_column -medium2'>
        <div class='demo'><span>-medium2</span></div>
      </div>
      <div class='grid_column -medium2'>
        <div class='demo'><span>-medium2</span></div>
      </div>
      <div class='grid_column -medium2'>
        <div class='demo'><span>-medium2</span></div>
      </div>
      <div class='grid_column -medium2'>
        <div class='demo'><span>-medium2</span></div>
      </div>
      <div class='grid_column -medium2'>
        <div class='demo'><span>-medium2</span></div>
      </div>
    </div>
    <div class='grid'>
      <div class='grid_column'>
        <div class='demo'>
          <span>grid_column</span>
          <div class='grid gapSmall'>
            <div class='grid_column'>
              <div class='demo'>
                <span>grid_column</span>
                <div class='grid gapSmall'>
                  <div class='grid_column -small6'>
                    <div class='demo'>
                      <span>-small6</span>
                      <div class='grid gapSmall'>
                        <div class='grid_column -small6'>
                          <div class='demo'>
                            <span>-small6</span>
                          </div>
                        </div>
                        <div class='grid_column -small6'>
                          <div class='demo'>
                            <span>-small6</span>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class='grid_column -small6'>
                    <div class='demo'>
                      <span>-small6</span>
                      <div class='grid gapSmall'>
                        <div class='grid_column -small6'>
                          <div class='demo'>
                            <span>-small6</span>
                          </div>
                        </div>
                        <div class='grid_column -small6'>
                          <div class='demo'>
                            <span>-small6</span>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>

      <div class='grid gapLarge'>
        <div class='grid_column'>
          <h1 class='sectionTitle'>Forms</h1>
          <form action='' class='settings form'>
                
            <div class='form_item formSwitch'>
              <label class='form_label formSwitch_wrapper' for='notifications'>Switch
                <input class='formSwitch_checkbox' type='checkbox' id='notifications' checked>
                <span class='formSwitch_custom'></span>
              </label>
            </div>

            <div class='form_item'>
              <label class='form_label' for='demoField1'>Basic input</label>
              <div class='form_field'>
                <input class="formInput" id='demoField1' type='text' placeholder='Basic input'>
              </div>
            </div>

            <div class='form_item -error'>
              <label class='form_label' for='demoField1'>Input with error</label>
              <div class='form_field'>
                <input class="formInput" id='demoField1' type='text' placeholder='Basic input'>
              </div>
              <div class='form_error'>This is an error message!</div>
            </div>

            <div class='form_item'>
              <label class='form_label' for='category'>Select</label>
              <div class='form_field customSelect'>
                <select class='formSelect customSelect_select -custom' id='category'>
                  <option>--</option>
                  <option>Item 1</option>
                  <option>Item 2</option>
                  <option>Item 3</option>
                </select>
                <a unselectable='on' class='customSelect_overlay'>--</a>
              </div>
            </div>

            <div class='form_item'>
              <label class='form_label' for='date'>Date input</label>
              <div class='form_item_help hide-for-js'>Example: 28/12/2014, or 28.12.2014</div>
              <div class='form_field'>
                <input class='formInput' type='date' placeholder='Day/Month/Year' inputDate>
              </div>
            </div>

            <div class='form_item'>
              <label class='form_label' for='time'>Time input</label>
              <div class='form_item_help hide-for-js'>Example: 14:30</div>
              <div class='form_field'>
                <input class='formInput' type='time' placeholder='Hour:Minutes' inputTime>
              </div>
            </div>

            <div class='form_item'>
              <label class='form_label' for=''>Switch</label>
              <div class='grid -collapse -clean'>
                <div class='grid_column -small6 form_subitem'>
                  <div class='bigRadio'>
                    <input class='bigRadio_input' type='radio' name='demoSwitch' value='1' id='demoSwitch1'>
                    <label class='bigRadio_label' for='demoSwitch1'>Answer 1</label>
                  </div>
                </div>
                <div class='grid_column -small6 form_subitem'>
                  <div class='bigRadio'>
                    <input class='bigRadio_input' type='radio' name='demoSwitch' value='2' id='demoSwitch2'>
                    <label class='bigRadio_label' for='demoSwitch2'>Answer 2</label>
                  </div>
                </div>
              </div>
            </div>

            <div class='form_item'>
              <label class='form_label' for='demoField3'>Textarea</label>
              <div class='form_field'>
                <textarea class='formTextarea' id='demoField3' placeholder='Lorem ipsum...'></textarea>
              </div>
            </div>
            
            <div class='form_item'>
              <div class='form_field'>
                <input class='button -primary -submit' type='submit' name='' value='Submit button'>
              </div>
            </div>

          </form>
        </div>
      </div>

      <div class='grid'>
        <div class='grid_column'>
          <h1 class='sectionTitle'>FAQ</h1>
          <ul class='faq' accordion>
            <li class='faq_item -open' accordionItem animate>
              <h2 class='faq_item_title'><?php echo $this->translate('What is MyUNHCR?'); ?></h2>
              <div class='faq_item_description preformat -compact' autoHeight animate>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia totam dolore, fugiat soluta quasi rem!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia totam dolore, fugiat soluta quasi rem!</p>
              </div>
            </li>
            <li class='faq_item' accordionItem animate>
              <h2 class='faq_item_title'><?php echo $this->translate('Is this application anonymous?'); ?></h2>
              <div class='faq_item_description preformat -compact' autoHeight animate>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia totam dolore, fugiat soluta quasi rem!</p>
              </div>
            </li>
            <li class='faq_item' accordionItem animate>
              <h2 class='faq_item_title'>Lorem Ipsum Dolor Sit</h2>
              <div class='faq_item_description preformat -compact' autoHeight animate>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia totam dolore, fugiat soluta quasi rem!</p>
              </div>
            </li>
          </ul>
        </div>
      </div>

    </div>
  </div>

</section>