<div id='relay' bodyClass="<?php echo $this->layout()->body_class; ?>"></div>
<section class='page'>

  <div class='sectionHeader'>
    <div class='grid'>
      <div class='grid_column'>
        <div class='sectionHeader_inner'>
          <h1 class='sectionHeader_title'><?php echo $this->translate("Survey");?></h1>
          <div id='sectionInfo_trigger' class='sectionHeader_info' unselectable='on'><i class='icon -infoBlack24'></i></div>
        </div>
      </div>
    </div>

    <div id='sectionInfo' class='sectionHeader_info_wrapper' animate>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_info_body preformat'>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati molestiae quod modi consequatur quae aliquid, doloremque id praesentium, quia voluptate ratione repudiandae dicta, ipsum expedita?</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>
      <form action='survey-finish.html' class='survey form' method='post' ajaxForm>

        <div class='form_item'>
          <label class='form_label' for='authentication'>Some input</label>
          <div class='form_field'>
            <input class='formInput' type='text' name=''>
          </div>
        </div>

        <div class='form_item'>
          <label class='form_label' for=''><?php echo $this->translate('What is your Gender ?'); ?></label>
          <div class='grid -collapse -clean'>
            <div class='grid_column -small6 form_subitem'>
              <div class='bigRadio'>
                <input class='bigRadio_input' type='radio' name='gender' value='male' id='gender-male'>
                <label class='bigRadio_label' for='gender-male'><?php echo $this->translate('I am Male'); ?></label>
              </div>
            </div>
            <div class='grid_column -small6 form_subitem'>
              <div class='bigRadio'>
                <input class='bigRadio_input' type='radio' name='gender' value='female' id='gender-female'>
                <label class='bigRadio_label' for='gender-female'><?php echo $this->translate('I am Female'); ?></label>
              </div>
            </div>
          </div>
        </div>

        <div class='grid -compact -reverse'>
          <div class='grid_column -small7'>
            <input class='button -primary -fullWidth' type='submit' value="<?php echo $this->translate('Finish'); ?>">
          </div>
          <div class='grid_column -small5'>
            <a class='button -fullWidth' href='take-a-survey.html' ajaxNav><?php echo $this->translate('Back'); ?></a>
          </div>
        </div>

      </form>
    </div>
  </div>
</section>
