<div id='relay' bodyClass="<?php echo $this->layout()->body_class; ?>"></div>
<section class='page'>

  <div class='sectionHeader'>
    <div class='sectionHeader_top'>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_top_inner'>
            <h1 class='sectionHeader_title'><?php echo $this->translate("Take a Survey");?></h1>
            <div id='sectionInfo_trigger' class='sectionHeader_info' unselectable='on'><i class='icon -infoBlack24'></i></div>
          </div>
        </div>
      </div>
    </div>
    <div id='sectionInfo' class='sectionHeader_bottom' animate>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_description preformat'>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati molestiae quod modi consequatur quae aliquid, doloremque id praesentium, quia voluptate ratione repudiandae dicta, ipsum expedita?</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>
<!--      <form action='survey-questions.html' class='survey form' method='post' ajaxForm>

        <div class='form_item'>
          <label class='form_label' for='authentication'><?php echo $this->translate('Please enter your identification number:'); ?></label>
          <div class='form_field'>
            <input class='formInput' type='text' name='' value='' placeholder='ID Number' id='authentication'>
          </div>
        </div>

        <div class='form_item'>
          <label class='form_label' for='date'><?php echo $this->translate('Please enter your date of birth:'); ?></label>
          <div class='form_item_help hide-for-js'>Example: 28/12/2014, or 28.12.2014</div>
          <div class='form_field'>
            <input class='formInput' type='date' placeholder='Day/Month/Year' inputDate>
          </div>
        </div>

        <div class='form_item'>
          <label class='form_label' for='chooseSurvey'><?php echo $this->translate('Choose your survey:'); ?></label>
          <div class='form_field customSelect'>
            <select class='formSelect customSelect_select -custom' id='chooseSurvey'>
              <option><?php echo $this->translate('Your needs assessment'); ?></option>
            </select>
            <a unselectable='on' class='customSelect_overlay'><?php echo $this->translate('Your needs assessment'); ?></a>
          </div>
        </div>

        <div class='grid -compact -reverse'>
          <div class='grid_column -small7'>
            <input class='button -primary -fullWidth' type='submit' value="<?php echo $this->translate('Next'); ?>">
          </div>
          <div class='grid_column -small5'>
            <a class='button -fullWidth' href='menu-page.html' ajaxNav tabindex='0'><?php echo $this->translate('Cancel'); ?></a>
          </div>
        </div>

      </form>-->

        <?php $form = $this->form; ?>
        <?php $form->setAttribute('class', 'survey form'); ?>
        <?php $form->setAttribute('action', $this->url('surveyQuestions'))->prepare(); ?>

        <?php echo $this->form()->openTag($form); ?>

        <div class='form_item'>
          <label class='form_label' for='authentication'><?php echo $this->translate('Please enter your identification number:'); ?></label>
          <div class='form_field'>
              <?php echo $this->formRow($form->get('authentification')); ?>
          </div>
        </div>

        <div class='form_item'>
          <label class='form_label' for='date'><?php echo $this->translate('Please enter your date of birth:'); ?></label>
          <div class='form_item_help hide-for-js'>Example: 28/12/2014, or 28.12.2014</div>
          <div class='form_field'>
              <?php echo $this->formRow($form->get('date')); ?>
          </div>
        </div>

        <?php if (count($form->get('survey')->getValueOptions()) < 1) { ?>
            <div><?php echo $this->translate('There is no survey available at this moment.'); ?></div>
        <?php } else { ?>

            <div class='form_item'>
                <label class='form_label' for='chooseSurvey'><?php echo $this->translate('Choose your survey:'); ?></label>
                <div class='form_field customSelect'>
                    <?php echo $this->formRow($form->get('survey')); ?>

                    <a unselectable='off' class='customSelect_overlay'><?php echo $this->translate('Choose Your needs assessment'); ?></a>
                </div>
            </div>

        <?php } ?>

        <div class='grid -compact -reverse'>
            <div class='grid_column -small7'>
                <input class='button -primary -fullWidth' type='submit' value="<?php echo $this->translate('Next'); ?>">
            </div>
            <div class='grid_column -small5'>
                <a class='button -fullWidth' href='menu-page.html' ajaxNav tabindex='0'><?php echo $this->translate('Cancel'); ?></a>
            </div>
        </div>

        <?php echo $this->form()->closeTag($form); ?>
    </div>
  </div>
</section>
