<section class='page'>

  <div class='sectionHeader'>
    <div class='grid'>
      <div class='grid_column'>
        <div class='sectionHeader_inner'>
          <h1 class='sectionHeader_title'><?php echo $this->translate("Update Personal Data");?></h1>
          <div id='sectionInfo_trigger' class='sectionHeader_info' unselectable='on'><i class='icon -infoBlack24'></i></div>
        </div>
      </div>
    </div>

    <div id='sectionInfo' class='sectionHeader_info_wrapper' animate>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_info_body preformat'>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati molestiae quod modi consequatur quae aliquid, doloremque id praesentium, quia voluptate ratione repudiandae dicta, ipsum expedita?</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>
      <form action='update-personal-data2.html' class='status form' ajaxForm>

        <div class='form_item'>
          <label class='form_label' for='authentication'><?php echo $this->translate('Please enter your identification number:'); ?></label>
          <div class='form_field'>
            <input class='formInput' type='text' name='' value='' placeholder='ID Number' id='authentication'>
          </div>
        </div>

        <div class='form_item'>
          <label class='form_label' for='date'><?php echo $this->translate('Please enter your date of birth:'); ?></label>
          <div class='form_field'>
            <input class='formInput' type='date' name='' value='' placeholder='' id='date'>
          </div>
        </div>

        <div class='grid'>
          <div class='grid_column -small5'>
            <div class='form_item'>
              <a class='button -submit' href="my-unhcr-services-menu.html"><?php echo $this->translate('Cancel'); ?></a>
            </div>
          </div>
          
          <div class='grid_column -small7'>
            <div class='form_item'>
              <input class='button -secondary -submit floatRight clearfix' type='submit' name='' value='Next'>
            </div>
          </div>
        </div>

      </form>
    </div>
  </div>
</section>
