<div id='relay' bodyClass="<?php echo $this->layout()->body_class; ?>"></div>
<section class='page'>

  <div class='sectionHeader'>
    <div class='sectionHeader_top'>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_top_inner'>
            <h1 class='sectionHeader_title'><?php echo $this->translate("Update Personal Data");?></h1>
            <div id='sectionInfo_trigger' class='sectionHeader_info' unselectable='on'><i class='icon -infoBlack24'></i></div>
          </div>
        </div>
      </div>
    </div>
    <div id='sectionInfo' class='sectionHeader_bottom' animate>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_description preformat'>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati molestiae quod modi consequatur quae aliquid, doloremque id praesentium, quia voluptate ratione repudiandae dicta, ipsum expedita?</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>
      <form action='update-personal-data2.html' class='status form' ajaxForm>

        <div class='form_item'>
          <label class='form_label' for='authentication'><?php echo $this->translate('Please enter your identification number:'); ?></label>
          <div class='form_field'>
            <input class='formInput' type='text' name='' value='' placeholder='ID Number' id='authentication'>
          </div>
        </div>

        <div class='form_item'>
          <label class='form_label' for='date'><?php echo $this->translate('Please enter your date of birth:'); ?></label>
          <div class='form_item_help hide-for-js'>Example: 28/12/2014, or 28.12.2014</div>
          <div class='form_field'>
            <input class='formInput' type='date' placeholder='Day/Month/Year' inputDate>
          </div>
        </div>

        <div class='grid -compact -reverse'>
          <div class='grid_column -small7'>
            <input class='inputSubmit button -primary -fullWidth' type='submit' name='' value="<?php echo $this->translate('Next'); ?>">
          </div>
          <div class='grid_column -small5'>
            <a class='button -fullWidth' href='menu-page.html' ajaxNav tabindex='0'><?php echo $this->translate('Cancel'); ?></a>
          </div>
        </div>

      </form>
    </div>
  </div>
</section>
