<section class='page'>

  <div class='sectionHeader'>
    <div class='grid'>
      <div class='grid_column'>
        <div class='sectionHeader_inner'>
          <h1 class='sectionHeader_title'>Update Personal Data</h1>
          <abbr class='sectionHeader_info'
            title='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos iste consequuntur quia illum qui minima.'
            ><i class='icon -infoBlack24'></i></abbr>
        </div>
      </div>
    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>
      <form action='update-personal-data2.html' class='status form'>

        <div class='form_item'>
          <label class='form_label' for='authentication'>Please enter your identification number:</label>
          <div class='form_field'>
            <input class='formInput' type='text' name='' value='' placeholder='ID Number' id='authentication'>
          </div>
        </div>

        <div class='form_item'>
          <label class='form_label' for='date'>Please enter your date of birth:</label>
          <div class='form_field'>
            <input class='formInput' type='date' name='' value='' placeholder='' id='date'>
          </div>
        </div>

        <div class='grid'>
          <div class='grid_column -small5'>
            <div class='form_item'>
              <a class='button -submit' href="my-unhcr-services-menu.html">Cancel</a>
            </div>
          </div>
          
          <div class='grid_column -small7'>
            <div class='form_item'>
              <input class='button -secondary -submit floatRight clearfix' type='submit' name='' value='Next'>
            </div>
          </div>
        </div>

      </form>
    </div>
  </div>
</section>