<?php echo $this->partial('application/index/header.phtml');?>

<section class='page'>

  <div class='sectionHeader'>
    <div class='grid'>
      <div class='grid_column'>
        <div class='sectionHeader_inner'>
          <h1 class='sectionHeader_title'>Update Personal Data</h1>
          <abbr class='sectionHeader_info'
            title='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos iste consequuntur quia illum qui minima.'
            ><i class='icon -infoBlack24'></i></abbr>
        </div>
      </div>
    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>
      <form action='update-personal-data4.html' class='incident form'>

        <h2 class='form_legend'>Enter Your New Address information:</h2>

        <div class='form_item'>
          <label class='form_label' for='country'>Country</label>
          <div class='form_field customSelect'>
            <select class='formSelect customSelect_select -custom' id='country'>
              <option>Jordan</option>
            </select>
            <a unselectable='on' class='customSelect_overlay'>Jordan</a>
          </div>
        </div>

        <div class='form_item'>
          <label class='form_label' for='city'>City:</label>
          <div class='form_field customSelect'>
            <select class='formSelect customSelect_select -custom' id='city'>
              <option>Amman</option>
            </select>
            <a unselectable='on' class='customSelect_overlay'>Amman</a>
          </div>
        </div>

        <div class='form_item'>
          <label class='form_label' for='address'>Street Address:</label>
          <div class='form_field'>
            <input class='formInput' type='text' name='' value='' placeholder='' id='address'>
          </div>
        </div>

        <div class='form_item'>
          <label class='form_label' for='postalCode'>Postal Code:</label>
          <div class='form_field'>
            <input class='formInput' type='text' name='' value='' placeholder='' id='postalCode'>
          </div>
        </div>

        <div class='form_item'>
          <label class='form_label' for='comments'>Comments:</label>
          <div class='form_field'>
            <input class='formInput' type='text' name='' value='' placeholder='' id='comments'>
          </div>
        </div>

        <div class='grid'>
          <div class='grid_column -small5'>
            <div class='form_item'>
              <a class='button -submit' href="refugee-feedback.html">Back</a>
            </div>
          </div>
          
          <div class='grid_column -small7'>
            <div class='form_item'>
              <input class='button -secondary -submit floatRight clearfix' type='submit' name='' value='Next'>
            </div>
          </div>
        </div>

      </form>
    </div>
  </div>
</section>

