<div id='relay' bodyClass="<?php echo $this->layout()->body_class; ?>"></div>
<section class='page'>

  <div class='sectionHeader'>
    <div class='sectionHeader_top'>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_top_inner'>
            <h1 class='sectionHeader_title'><?php echo $this->translate("Update Personal Data");?></h1>
            <div id='sectionInfo_trigger' class='sectionHeader_info' unselectable='on'><i class='icon -infoBlack24'></i></div>
          </div>
        </div>
      </div>
    </div>
    <div id='sectionInfo' class='sectionHeader_bottom' animate>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_description preformat'>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati molestiae quod modi consequatur quae aliquid, doloremque id praesentium, quia voluptate ratione repudiandae dicta, ipsum expedita?</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>
      
      <h2 class='form_legend'><?php echo $this->translate('Please confirm your new address:'); ?></h2>
      <div class='preformat gapSmall'>
        <p>05, Abdul Larea, Al-Azzeh Street, Deir Ghbar, Amman, Jordan</p>
      </div>

      <div class='grid -compact -reverse'>
        <div class='grid_column -small7'>
          <input class='inputSubmit button -primary -fullWidth' type='submit' name='' value="<?php echo $this->translate('Confirm'); ?>">
        </div>
        <div class='grid_column -small5'>
          <a class='button -fullWidth' href='update-personal-data3.html' ajaxNav tabindex='0'><?php echo $this->translate('Back'); ?></a>
        </div>
      </div>

    </div>
  </div>

</section>