<div id='relay' bodyClass="<?php echo $this->layout()->body_class; ?>"></div>
<section class='page'>

  <div class='sectionHeader'>
    <div class='sectionHeader_top'>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_top_inner'>
            <h1 class='sectionHeader_title'><?php echo $this->translate("Update Personal Data");?></h1>
            <div id='sectionInfo_trigger' class='sectionHeader_info' unselectable='on'><i class='icon -infoBlack24'></i></div>
          </div>
        </div>
      </div>
    </div>
    <div id='sectionInfo' class='sectionHeader_bottom' animate>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_description preformat'>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati molestiae quod modi consequatur quae aliquid, doloremque id praesentium, quia voluptate ratione repudiandae dicta, ipsum expedita?</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='grid'>
    <div class='grid_column -medium9 -mediumPlus8'>
      <form action='update-personal-data4.html' class='incident form' ajaxForm>

        <h2 class='form_legend'><?php echo $this->translate('Enter Your New Address information:'); ?></h2>

        <div class='form_item'>
          <label class='form_label' for='country'><?php echo $this->translate('Country'); ?></label>
          <div class='form_field customSelect'>
            <select class='formSelect customSelect_select -custom' id='country'>
              <option>Jordan</option>
            </select>
            <a unselectable='on' class='customSelect_overlay'>Jordan</a>
          </div>
        </div>

        <div class='form_item'>
          <label class='form_label' for='city'><?php echo $this->translate('City:'); ?></label>
          <div class='form_field customSelect'>
            <select class='formSelect customSelect_select -custom' id='city'>
              <option>Amman</option>
            </select>
            <a unselectable='on' class='customSelect_overlay'>Amman</a>
          </div>
        </div>

        <div class='form_item'>
          <label class='form_label' for='address'><?php echo $this->translate('Street Address:'); ?></label>
          <div class='form_field'>
            <input class='formInput' type='text' name='' value='' placeholder='' id='address'>
          </div>
        </div>

        <div class='form_item'>
          <label class='form_label' for='postalCode'><?php echo $this->translate('Postal Code:'); ?></label>
          <div class='form_field'>
            <input class='formInput' type='text' name='' value='' placeholder='' id='postalCode'>
          </div>
        </div>

        <div class='form_item'>
          <label class='form_label' for='comments'><?php echo $this->translate('Comments:'); ?></label>
          <div class='form_field'>
            <input class='formInput' type='text' name='' value='' placeholder='' id='comments'>
          </div>
        </div>

        <div class='grid -compact -reverse'>
          <div class='grid_column -small7'>
            <input class='inputSubmit button -primary -fullWidth' type='submit' name='' value="<?php echo $this->translate('Next'); ?>">
          </div>
          <div class='grid_column -small5'>
            <a class='button -fullWidth' href='update-personal-data2.html' ajaxNav tabindex='0'><?php echo $this->translate('Back'); ?></a>
          </div>
        </div>

      </form>
    </div>
  </div>
</section>
