<section class='page'>

  <div class='sectionHeader'>
    <div class='grid'>
      <div class='grid_column'>
        <div class='sectionHeader_inner'>
          <h1 class='sectionHeader_title'>Update Personal Data</h1>
          <abbr class='sectionHeader_info'
            title='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos iste consequuntur quia illum qui minima.'
            ><i class='icon -infoBlack24'></i></abbr>
        </div>
      </div>
    </div>
  </div>

  <div class='personalData_body'>
    <div class='grid'>
      <div class='grid_column -medium9 -mediumPlus8'>

        <h2 class='form_legend'>Thank you!</h2>

        <p class='personalData_preformat'>Your new address follows:</p>

        <p class='personalData_newData'>05, Abdul Larea, Al-Azzeh Street, Deir Ghbar, Amman, Jordan</p>

        <p class='personalData_preformat -preformatGap'>Please confirm the change with the button below.</p>

        <a class='button -primary -submit floatRight clearfix' href='my-unhcr-services-menu.html' title=''>Send</a>
      </div>
    </div>
  </div>

</section>