<section class='page'>

  <div class='sectionHeader'>
    <div class='grid'>
      <div class='grid_column'>
        <div class='sectionHeader_inner'>
          <h1 class='sectionHeader_title'>Update Personal Data</h1>
          <div id='sectionInfo_trigger' class='sectionHeader_info' unselectable='on'><i class='icon -infoBlack24'></i></div>
        </div>
      </div>
    </div>

    <div id='sectionInfo' class='sectionHeader_info_wrapper' animate>
      <div class='grid -clean'>
        <div class='grid_column'>
          <div class='sectionHeader_info_body preformat'>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati molestiae quod modi consequatur quae aliquid, doloremque id praesentium, quia voluptate ratione repudiandae dicta, ipsum expedita?</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='personalData_body'>
    <div class='grid'>
      <div class='grid_column -medium9 -mediumPlus8'>

        <h2 class='form_legend'>Thank you!</h2>

        <p class='personalData_preformat'>Your new address follows:</p>

        <p class='personalData_newData'>05, Abdul Larea, Al-Azzeh Street, Deir Ghbar, Amman, Jordan</p>

        <p class='personalData_preformat -preformatGap'>Please confirm the change with the button below.</p>

        <a class='button -primary -submit floatRight clearfix' href='my-unhcr-services-menu.html' title=''>Send</a>
      </div>
    </div>
  </div>

</section>