<?php echo $this->partial('application/index/header.phtml');?>

<section class='page'>
  <div class='grid'>
    <div class='grid_column'>
      <h1 class='sectionTitle'>Survey</h1>
      <span class='tooltip'></span>

      <form action='refugee-feedback.html' class='survey form'>
        
        <div class='grid'>
          <div class='grid_column -medium9 -mediumPlus8'>

          <div class='grid'>
            <div class='grid_column -small6'>
              <div class='form_item'>
                <label class='form_label' for='male'>I am Male</label>
                <div class='form_field'>
                  <input type='radio' name='' value='' placeholder='' id='male'>
                </div>
              </div>
            </div>

            <div class='grid_column -small6'>
              <div class='form_item'>
                <label class='form_label' for='female'>I am Female</label>
                <div class='form_field'>
                  <input type='radio' name='' value='' placeholder='' id='female'>
                </div>
              </div>
            </div>
          </div>

          <div class='grid'>
            <div class='grid_column -small5'>
              <div class='form_item'>
                <a class='button -submit' href="choose-your-survey.html">Back</a>
              </div>
            </div>
            
            <div class='grid_column -small7'>
              <div class='form_item'>
                <input class='button -secondary -submit' type='submit' name='' value='Next'>
              </div>
            </div>
          </div>

          </div>
        </div><!-- /grid -->

      </form>
    </div>
  </div>
</section>

