<?php echo $this->partial('application/index/header.phtml');?>
    <section class='page'>
        <div class='row'>
            <div class='small-12 columns page-title margin-t10'>
                <h4>Select your settings:</h4>
            </div>
        </div>
        <form class='margin-t10 margin-b20' action='yourSettings_submit' method='get' accept-charset='utf-8'>
            <div class='row margin-b20'>
                <div class='small-6 columns'>
                    <label for='onoffswitch'><h5>Notifications:</h5></label>
                </div>
                <div class='small-6 columns'>
                    <div class='onoffswitch right'>
                        <input type='checkbox' name='onoffswitch' class='onoffswitch-checkbox' id='onoffswitch' checked>
                        <label class='onoffswitch-label' for='onoffswitch'>
                            <span class='onoffswitch-inner'></span>
                            <span class='onoffswitch-switch'></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class='row'>
                <div class='small-12 columns'>
                    <label for='language'><h5>Language</h5></label>
                    <select id='language'>
                        <option value='0' selected='selected'>English</option>
                        <option>Croatian</option>
                        <option>Deutsch</option>
                    </select>
                </div>
            </div>
            <div class='row'>
                <div class='small-12 columns'>
                    <label for='country'><h5>Country</h5></label>
                    <select id='country'>
                        <option value='0' selected='selected'>Jordan</option>
                    </select>
                </div>
            </div>
            <div class='row'>
                <div class='small-12 columns'>
                    <label for='category'><h5>Category</h5></label>
                    <select id='category'>
                        <option value='0' selected='selected'>Refugees</option>
                    </select>
                </div>
            </div>
            <div class='row'>
                <div class='small-12 columns'>
                    <label for='location'><h5>Location</h5></label>
                    <select id='location'>
                        <option value='0' selected='selected'>Ammon</option>
                    </select>
                </div>
            </div>
        </form>
    </section><!-- /page -->
<?php echo $this->partial('application/index/footer-save.phtml');?>