
<div class="separator bottom"></div>

<div class="heading-buttons">
    <h3 class="glyphicons display"> <?php echo $this->translate('Dashboard'); ?></h3>
    <div class="clearfix" style="clear: both;"></div>
</div>

<div class="separator bottom"></div>

<div class="innerLR">
    <div class="row">
        <div class="col-md-8">
            <div class="widget widget-4 margin-none">
                <div class="widget-head">
                    <h4 class="heading"><?php echo $this->translate('Active country'); ?></h4>
                </div>
                <div class="widget-body">
                    <?php if (isset($_SESSION['countrySettings']['countryName'])) { ?>
                        <h4><?php echo $_SESSION['countrySettings']['countryName']; ?></h4>
                    <?php } else { ?>
                        <h4><?php echo $this->translate('Please choose country in top navigation'); ?></h4>
                    <?php } ?>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="row">
                <div class="col-md-12">
                    <a href="" class="widget-stats">
                        <span class="glyphicons group"></span>
                        <span class="txt"><strong><?php echo count($this->users); ?></strong><?php echo $this->translate(' users'); ?></span>
                        <div class="clearfix"></div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="separator bottom"></div>

<div class="innerLR">
    <div class="row">
        <div class="col-md-6">
            <div class="widget widget-4">
                <div class="widget-head">
                    <h4 class="heading"><?php echo $this->translate('Overview'); ?></h4>
                </div>
                <div class="separator bottom"></div>
                <div class="col-md-12">
                    <div class="btn-group btn-group-vertical block">
                        <a class="btn btn-icon btn-default btn-block glyphicons keynote count">
                            <span><?php echo count($this->news); ?></span><?php echo $this->translate('News'); ?></a>
                        <a class="btn btn-icon btn-default btn-block glyphicons comments count">
                            <span><?php echo count($this->faqs); ?></span><?php echo $this->translate('FAQ\'s'); ?></a>
                        <a class="btn btn-icon btn-default btn-block glyphicons notes_2 count">
                            <span><?php echo count($this->surveys); ?></span><?php echo $this->translate('Surveys'); ?></a>
                    </div>
                </div>
                <div class="separator bottom"></div>
                <div class="col-md-12">
                    <div class="btn-group btn-group-vertical block">
                        <a class="btn btn-icon btn-default btn-block glyphicons circle_info count">
                            <span><?php echo count($this->services); ?></span><?php echo $this->translate('Services'); ?></a>
                        <a class="btn btn-icon btn-default btn-block glyphicons group count">
                            <span><?php echo count($this->organizations); ?></span><?php echo $this->translate('Organizations'); ?></a>
                        <a class="btn btn-icon btn-default btn-block glyphicons kiosk count">
                            <span><?php echo count($this->activities); ?></span><?php echo $this->translate('Activities'); ?></a>
                        <a class="btn btn-icon btn-default btn-block glyphicons global count">
                            <span><?php echo count($this->sectors); ?></span><?php echo $this->translate('Sectors'); ?></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="widget widget-4">
                <div class="widget-head">
                    <h4 class="heading"><?php echo $this->translate('Users'); ?></h4>
                </div>
                <div class="separator bottom"></div>
                <div class="col-md-12">
                    <div class="btn-group btn-group-vertical block">
                        <?php foreach ($this->users as $user) { ?>
                            <a class="btn btn-icon btn-default btn-block glyphicons user count">
                                <span><small><?php echo $user->getType(); ?></small></span>
                                <?php echo $user->getEmail(); ?>
                            </a>
                        <?php } ?>
                    </div>
                </div>
            </div>
            <div class="widget widget-4">
                <div class="widget-head">
                    <h4 class="heading"><?php echo $this->translate('From clients'); ?></h4>
                </div>
                <div class="separator bottom"></div>
                <div class="col-md-12">
                    <div class="btn-group btn-group-vertical block">
                        <a class="btn btn-icon btn-default btn-block glyphicons user count">
                            <span><?php echo count($this->incidents); ?></span><?php echo $this->translate('Incidents'); ?>
                        </a>
                        <a class="btn btn-icon btn-default btn-block glyphicons user count">
                            <span><?php echo count($this->complaints); ?></span><?php echo $this->translate('Complaints'); ?>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="innerLR">
    <div class="row">
        <div class="col-md-12">
            <div class="widget widget-4">
                <div class="widget-head">
                    <h4 class="heading"><?php echo $this->translate('Appointments'); ?></h4>
                </div>
                <div class="separator bottom"></div>
                <div class="col-md-12">
                    <div class="widget widget-2 widget-tabs">
                        <div class="widget-head">
                            <ul>
                                <?php $active = true; ?>
                                <?php foreach ($this->appointmentCategories as $ac) { ?>
                                    <?php if ($active) { ?>
                                        <li class="active">
                                            <a class="glyphicons conversation"
                                            href="#<?php echo $ac->getId(); ?>" data-toggle="tab">
                                                <?php echo $ac->getCategory(); ?></a>
                                        </li>
                                        <?php $active = false; ?>
                                    <?php } else { ?>
                                        <li>
                                            <a class="glyphicons conversation"
                                               href="#<?php echo $ac->getId(); ?>" data-toggle="tab">
                                                <?php echo $ac->getCategory(); ?></a>
                                        </li>
                                    <?php } ?>
                                <?php } ?>
                            </ul>
                        </div>
                        <div class="widget-body">
                            <div class="tab-content" style="overflow: hidden">
                                <?php $active = true; ?>
                                <?php foreach ($this->appointmentCategories as $category) { ?>
                                    <?php if ($active) { ?>
                                        <div class="tab-pane active" id="<?php echo $category->getId(); ?>">
                                            <?php $count = 0; ?>
                                            <?php foreach ($this->appointments as $ap) { ?>
                                                <?php if ($ap->getCategory() == $category) { ?>
                                                    <div class="well margin-none col-md-2" data-row="row_<?php echo $ap->getId(); ?>">
                                                        <address class="margin-none">
                                                            <strong><?php echo date_format($ap->getDate(), 'd.m.Y'); ?></strong>
                                                            <?php echo $this->translate('at'); ?>
                                                            <strong><?php echo date_format($ap->getTime(), 'H:i'); ?></strong><br>
                                                            <abbr title="Work email"><?php echo $this->translate('Auth ID'); ?>:</abbr>
                                                            <?php echo $ap->getAuthId(); ?><br/>
                                                            <abbr title="Work Phone"><?php echo $this->translate('From'); ?>:</abbr>
                                                            <?php echo $ap->getCountry()->getName(); ?><br/>
                                                        </address>
                                                    </div>
                                                    <?php $count++; ?>
                                                <?php } ?>
                                                <?php if ($count == 12) break;?>
                                            <?php } ?>
                                        </div>
                                        <?php $active = false; ?>
                                    <?php } else { ?>
                                        <div class="tab-pane" id="<?php echo $category->getId(); ?>">
                                            <?php $count = 0; ?>
                                            <?php foreach ($this->appointments as $ap) { ?>
                                                <?php if ($ap->getCategory() == $category) { ?>
                                                    <div class="well margin-none col-md-2" data-row="row_<?php echo $ap->getId(); ?>">
                                                        <address class="margin-none">
                                                            <strong><?php echo date_format($ap->getDate(), 'd.m.Y'); ?></strong>
                                                            <?php echo $this->translate('at'); ?>
                                                            <strong><?php echo date_format($ap->getTime(), 'H:i'); ?></strong><br>
                                                            <abbr title="Work email"><?php echo $this->translate('Auth ID'); ?>:</abbr>
                                                            <?php echo $ap->getAuthId(); ?><br/>
                                                            <abbr title="Work Phone"><?php echo $this->translate('From'); ?>:</abbr>
                                                            <?php echo $ap->getCountry()->getName(); ?><br/>
                                                        </address>
                                                    </div>
                                                    <?php $count++; ?>
                                                <?php } ?>
                                                <?php if ($count == 12) break;?>
                                            <?php } ?>
                                        </div>
                                    <?php } ?>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
